plenum/__metadata__.py
plenum/cli/cli.py
plenum/client/client.py
plenum/common/signer_did.py
plenum/common/signer_simple.py
plenum/common/signing.py
plenum/common/stack_manager.py
plenum/common/stacked.py
plenum/common/util.py
plenum/server/client_authn.py
plenum/test/cli/helper.py
plenum/test/cli/test_cli_client_port.py
plenum/test/conftest.py
plenum/test/helper.py
plenum/test/pool_transactions/test_client_with_pool_txns.py
plenum/test/primary_selection/test_primary_selection.py
plenum/test/replica/test_primary_marked_suspicious_for_sending_prepare.py
plenum/test/testing_utils.py
plenum/test/view_change/test_instance_change_msg_checking.py

Daniel, please review and accept (if looks good) this pull request. This contains fix for intermittent send claim failure issue.

Send claim fix

---

plenum/cli/cli.py
plenum/test/pool_transactions/test_suspend_node.py

Skipped a failing test cases and all other dependent pipelines were getting impacted

Skipped a failing test cases and all other dependent pipelines were getting impacted

---

plenum/cli/cli.py

minor refactoring and fixing one case sensitive wallet path issue

minor refactoring and fixing one case sensitive wallet path issue

---

plenum/cli/cli.py
plenum/cli/constants.py
plenum/test/cli/HelpMsg.py
plenum/test/cli/test_help_command.py

changes related to how help command works and added check that we have all help message for all supported cli commands

changes related to how help command works and added check that we have all help message for all supported cli commands

---

plenum/cli/cli.py
plenum/cli/constants.py
plenum/test/cli/HelpMsg.py
plenum/test/cli/conftest.py
plenum/test/cli/helper.py
plenum/test/cli/test_help_command.py
plenum/test/cli/test_save_and_restore_wallet.py

fixed cli wallet persistence related bug

fixed cli wallet persistence related bug

---

plenum/test/node_catchup/test_discard_view_no.py
plenum/test/script/test_change_non_primary_node_ha.py
plenum/test/script/test_change_primary_node_ha.py

fixed two failing test cases

---

plenum/config.py
plenum/server/primary_elector.py

increase connect timeout for nodes and also added some logs to cli so that it can be asserted in sovrin client

increase connect timeout for nodes and also added some logs to cli so that it can be asserted in sovrin client

---

plenum/cli/cli.py
plenum/cli/command.py
plenum/cli/constants.py
plenum/common/exceptions.py
plenum/common/util.py
plenum/persistence/orientdb_store.py
plenum/server/primary_elector.py
plenum/test/cli/test_basic_node_commands.py
plenum/test/cli/test_help_command.py
plenum/test/test_client.py

fixes in help commands, few other minor bug fixes

fixes in help commands, few other minor bug fixes

---

plenum/common/stacked.py
plenum/common/util.py
plenum/test/script/test_add_unregistered_remote.py
plenum/test/test_node.py
plenum/test/test_stack.py
plenum/test/testable.py

[Closes SOV-608] Fixed Bug: Security - When a potential validator contacts pool a json is created for it before adding it to the pool

[Closes SOV-608] Fixed Bug: Security - When a potential validator contacts pool a json is created for it before adding it to the pool

---

plenum/common/log.py
plenum/config.py

Implementation of disabling logging to stdout

Option for disabling logging to stdout

---

plenum/common/exceptions.py
plenum/common/util.py

*Tests*
- `testStartNewAgentOnUsedPort` in sovrin-client
- `testStartAgentChecksForPortAvailability ` in sovrin-client

[SOV-768] Fixed port not available exception on windows and linux based systems

---

plenum/test/test_client.py

There is missing import of OP_FIELD_NAME

Fix imports in test_client.py

---

plenum/test/node_catchup/test_new_node_catchup.py
setup.py

This pull request changes required version of stp to 0.1.26

Up version of stp to 0.1.26

---

plenum/test/instances/test_instance_cannot_become_active_with_less_than_four_servers.py
plenum/test/script/test_change_non_primary_node_ha.py

Skip test testProtocolInstanceCannotBecomeActiveWithLessThanFourServers and testChangeNodeHaForNonPrimary

Skip failing tests

---

Jenkinsfile

common API for windows and unix (installation and testing)

switched to new API from shared lib

---

Jenkinsfile

common API for windows and unix (installation and testing)

updated to use new API from shared lib

---

plenum/common/script_helper.py
plenum/test/primary_election/test_primary_election_case1.py
plenum/test/primary_election/test_primary_election_case4.py
plenum/test/primary_election/test_primary_election_case5.py
plenum/test/script/helper.py
plenum/test/script/test_change_non_primary_node_ha.py
plenum/test/test_node.py
plenum/test/waits.py
plenum/test/zstack_tests/test_zstack_reconnection.py

Fixes failing test testChangeNodeHaForNonPrimary

Fix testChangeNodeHaForNonPrimary

---

plenum/server/node.py
plenum/test/script/helper.py
plenum/test/script/test_change_primary_node_ha.py

Fix failing test testChangeNodeHaForPrimary

Fix test testChangeNodeHaForPrimary

---

Jenkinsfile
plenum/test/cli/test_cli_with_auction_req_plugin.py
plenum/test/view_change/test_master_primary_different_from_previous.py

Skip some broken tests
Remov edevelopment options from Jenkinsfile

Fix post 3pc-batch merge

---

plenum/client/client.py
setup.py

- Remove force reconnection from retryForExpected - it was causing message loss
- Refactor code

Fix redundant reconnections and refactor

---

plenum/common/ledger.py
plenum/common/stack_manager.py
plenum/server/node.py
plenum/test/monitoring/test_instance_change_with_Delta.py
plenum/test/node_catchup/test_node_request_missing_transactions.py
setup.py

Remove initialization of domain ledger - now it is done by ledger and file store which knows how to do it

Make changes to support ChunkedFileStore

---

plenum/cli/cli.py
plenum/common/messages/client_request.py
plenum/common/messages/fields.py
plenum/common/util.py
plenum/server/pool_manager.py
plenum/server/pool_req_handler.py
plenum/test/pool_transactions/helper.py
plenum/test/pool_transactions/test_nodes_with_pool_txns.py

* fix message validation 
* fix cli command check

Fixes for INDY-71

---

plenum/client/pool_manager.py
plenum/server/node.py
plenum/server/pool_manager.py
plenum/server/replica.py
plenum/test/helper.py
plenum/test/node_catchup/helper.py
plenum/test/node_catchup/test_catchup_demoted.py
plenum/test/node_catchup/test_node_catchup_after_disconnect.py

- Fixed the problem with catch-up of disconnected nodes;
- Fixed demotion (suspension) of nodes
- Fixed the problem with catch-up of demoted nodes

Catch up demoted

---

plenum/common/ledger_manager.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/batching_3pc/catch-up/test_state_reverted_before_catchup.py
plenum/test/batching_3pc/helper.py
plenum/test/checkpoints/test_stable_checkpoint.py
plenum/test/node_catchup/test_node_catchup_after_lost_connection.py
plenum/test/test_node.py

- Revert unordered batches before starting catch-up (not after)
- GC batches

Revert unordered batches before starting catch-up (not after)

---

plenum/server/replica.py
plenum/test/node_request/test_pre_prepare/test_ignore_pre_prepare_pp_seq_no_less_than_expected.py

* ignore pp requests with ppSeqNo less than expected
* minor refactor

Do not enqueue old pre-prepares

---

plenum/test/input_validation/message_validation/test_commit_message.py
plenum/test/input_validation/message_validation/test_consistencyproof_message.py
plenum/test/input_validation/message_validation/test_instanceChange_message.py
plenum/test/input_validation/message_validation/test_ledgerstatus_message.py
plenum/test/input_validation/message_validation/test_nomination_message.py
plenum/test/input_validation/message_validation/test_ordered_message.py
plenum/test/input_validation/message_validation/test_prepare_message.py
plenum/test/input_validation/message_validation/test_preprepare_message.py
plenum/test/input_validation/message_validation/test_primary_message.py
plenum/test/input_validation/message_validation/test_propagate_message.py
plenum/test/input_validation/message_validation/test_reelection_message.py

Brings tests for implemented messages

Add tests for node to node messages

---

plenum/common/messages/fields.py
plenum/common/types.py
plenum/test/input_validation/fields_validation/test_serializedvalue_field.py
plenum/test/input_validation/message_validation/test_batch_message.py
plenum/test/input_validation/message_validation/test_checkpoint_meeting.py
plenum/test/input_validation/message_validation/test_threepcstate_message.py

Validation for following messages:
- Checkpoint
- ThreePCState
- Batch

Validation for state messages

---

plenum/server/quorums.py
plenum/test/node_catchup/conftest.py
plenum/test/node_catchup/test_catchup_f_plus_one.py

Set consensus for catchup to f+1

Catchup f one

---

plenum/server/node.py
plenum/server/replica.py
plenum/test/checkpoints/test_basic_checkpointing.py
plenum/test/node_catchup/test_node_catchup_after_checkpoints.py

* start the catchup procedure if a node going to stash second CHECKPOINT
* minor refactor
* add TODOs

Catchup if 3pc messages are missed, INDY-335

---

plenum/server/propagator.py
plenum/server/replica.py
plenum/test/helper.py
plenum/test/view_change/helper.py
plenum/test/view_change/slow_nodes/test_view_change_gc_all_nodes_random_delay.py

fixes tests:
- test_view_change_all_nodes_random_delay.py
- test_view_change_complex.py

fix garbage collecting logic to use 3PCKey instead of ppSeqNo (INDY-400)

---

plenum/__metadata__.py

Also sets __author__ = "Hyperledger"

Release v1.0 (DO NOT MERGE)

---

plenum/server/replica.py
plenum/test/primary_selection/test_recover_more_than_f_failure.py

Does not recover backup replica.

Recover primary checkpoint functionality after a crash

---

plenum/test/cli/test_long_msg_err.py
stp_core/config.py
stp_zmq/test/test_zstack.py

- Need to think about a lower value for max msg length;
- currently low value leads to problems with batching on transport level

increase max msg length temporarily

---

README.md
ledger/genesis_txn/genesis_txn_file_util.py
plenum/cli/cli.py
plenum/client/pool_manager.py
plenum/client/wallet.py

Merged hotfixes from stable for wallet and genesis pool transactions file migration and readme file.

Merged hotfixes from stable 1.1.24

---

plenum/test/cli/test_long_msg_err.py
stp_core/config.py
stp_zmq/test/test_zstack.py

This reverts commit 1ba2d758d3fd0be92325ea223633584bb69d2552.

Revert "Merge pull request #358 from hyperledger/increase-mx-size-limit"

---

plenum/server/node.py
plenum/test/test_dirty_read.py

INDY-761.
Outbox of replicas was services before inbox and before processing new requests.

Fix dirty reads

---

examples/new_client.py
plenum/cli/__main__.py
plenum/test/conftest.py
plenum/test/test_action_queue.py
scripts/load.py
scripts/plenum
scripts/start_plenum_node
stp_core/config.py
stp_raet/test/conftest.py
stp_zmq/test/conftest.py

Now debug flag for Looper class is got from config.
NOTE: for tests debug flag for Looper class is left as default (False)
or set to False explicitly.

INDY-716: configurable debug for Looper class

---

common/serializers/serialization.py
plenum/common/constants.py
plenum/common/messages/client_request.py
plenum/common/messages/fields.py
plenum/common/messages/message_base.py
plenum/common/plenum_protocol_version.py
plenum/common/request.py
plenum/common/types.py
plenum/test/client/test_client.py
plenum/test/client/test_protocol_version.py
plenum/test/client/test_request.py
plenum/test/helper.py
plenum/test/input_validation/fields_validation/test_protocol_version_field.py
plenum/test/input_validation/message_validation/test_client_message.py
plenum/test/input_validation/test_client_request.py
plenum/test/input_validation/test_client_safe_request.py

- supported Protocol Version in Request
- use Version=1 (state proofs support) by default
- fix a couple of issues with validation
- added tests (including some missing tests for validation)

INDY-877: Protocol version support

---

ci/code-validation.dockerfile

fixed apt-get update / install in dockerfile for static code validation

---

plenum/client/wallet.py
plenum/common/request.py
plenum/test/cli/helper.py
plenum/test/cli/test_log_filtering.py
plenum/test/client/test_protocol_version.py
plenum/test/helper.py
plenum/test/input_validation/test_client_safe_request.py
plenum/test/pool_transactions/test_get_txn_request.py
plenum/test/validator_info/test_validator_info.py

INDY-877: do not set protocol version be default in Requests

---

plenum/client/client.py

Signed-off-by: Victor Muzychenko <mzkvct@gmail.com>

Fix sending and expecting for a list of connecteds

---

plenum/client/client.py
plenum/client/pool_manager.py
plenum/common/stack_manager.py
plenum/server/node.py
plenum/server/pool_manager.py
plenum/server/quorums.py
plenum/test/client/test_client_sends_get_request_to_one_node.py
plenum/test/common/test_parse_ledger.py
plenum/test/common/test_pool_file_raises_descriptive_error.py
plenum/test/helper.py
plenum/test/monitoring/test_instance_change_with_Delta.py
plenum/test/primary_selection/test_primary_selection_after_demoted_node_promotion.py
plenum/test/primary_selection/test_recover_more_than_f_failure.py
plenum/test/test_performance.py

- call pool parameters adjustment method when promotion happens for previously demoted node
- made renaming for some method names
- added test

Adjust pool parameters when demoted node is promoted again (INDY-848)

---

Jenkinsfile.ci

fixed labels routine

---

plenum/common/ledger_manager.py
plenum/test/node_catchup/test_large_catchup.py

This PR fixes gaps in catchup of large ledgers

[INDY-907] Fix gaps in catchup

---

common/serializers/serialization.py
crypto/bls/bls_crypto.py
crypto/bls/bls_multi_signature.py
crypto/bls/indy_crypto/bls_crypto_indy_crypto.py
crypto/test/bls/indy_crypto/test_bls_crypto_indy_crypto.py
crypto/test/test_multi_signature.py

INDY-928: use msgpack for serialization of multi-sig value

---

README.md

INDY-754: update readme

---

crypto/bls/bls_multi_signature.py
plenum/client/client.py
plenum/test/bls/helper.py
plenum/test/bls/test_add_bls_key.py
plenum/test/bls/test_add_incorrect_bls_key.py
plenum/test/bls/test_update_incorrect_bls_key.py
plenum/test/client/test_client_can_send.py
plenum/test/delayers.py
plenum/test/exceptions.py
plenum/test/helper.py
plenum/test/test_node.py

- Added can_send methods to client
- Fixed waiting for catch-up for clients when sending read requests

INDY-941: Added can_send methods to client

---

plenum/common/startable.py
plenum/test/client/test_client_can_send.py

INDY-941: fix startable methods to take into account None mode

---

setup.py

Do not make folders in setup.py

---

plenum/server/domain_req_handler.py
plenum/test/bls/test_state_proof.py

INDY-949: fix making state proofs to use committed state root

---

plenum/client/client.py

Fix client basedir initialization

---

crypto/bls/indy_crypto/bls_crypto_indy_crypto.py

do not show DEBUG logs from indy-crypto

---

Jenkinsfile.ci
ci/build_base_image.sh
ci/ubuntu.dockerfile
setup.py

[INDY-945, INDY-900, INDY-530] hierarchy of docker images, docker build automation via make, test env setup

---

plenum/server/replica.py
plenum/server/suspicion_codes.py

remove incorrect BLS error code

---

plenum/test/logging/test_logging_txn_state.py

Fix logging tests

---

plenum/common/test_network_setup.py

Fix overwriting of client genesis txns.

---

runner.py

Fix runner.py to handle errors

---

plenum/server/node.py
plenum/server/view_change/view_changer.py
plenum/test/primary_selection/test_new_node_accepts_chosen_primary.py

[INDY-480] fixes for comments in PR #470

---

ci/ubuntu.dockerfile
crypto/bls/indy_crypto/bls_crypto_indy_crypto.py
crypto/test/bls/indy_crypto/test_bls_crypto_indy_crypto.py
plenum/test/bls/test_bls_bft_replica.py
setup.py

- increment indy-crypto to the latest stable;
- improve bls crypto tests;
- get rid of tmp fixes for length in crypto
- added more tests

IS-403: Bump indy crypto

---

plenum/cli/cli.py
plenum/common/config_helper.py
plenum/server/general_config/ubuntu_platform_config.py
plenum/server/node.py
plenum/server/validator_info_tool.py
plenum/test/conftest.py
plenum/test/node_catchup/test_node_catchup_after_restart_after_txns.py
plenum/test/node_catchup/test_node_catchup_after_restart_no_txns.py
plenum/test/plugin/stats_consumer/plugin_stats_consumer.py
plenum/test/pool_transactions/helper.py
plenum/test/pool_transactions/test_change_ha_persists_post_nodes_restart.py
plenum/test/pool_transactions/test_client_with_pool_txns.py
plenum/test/pool_transactions/test_nodes_ha_change_back.py
plenum/test/pool_transactions/test_z_node_key_changed.py
plenum/test/primary_selection/test_primary_selection_after_primary_demotion_and_pool_restart.py
plenum/test/script/helper.py
plenum/test/test_node.py
plenum/test/test_node_connection.py
plenum/test/test_state_regenerated_from_ledger.py
plenum/test/validator_info/test_validator_info.py
plenum/test/view_change/helper.py
plenum/test/zstack_tests/test_zstack_reconnection.py

INDY-878: move validator info files back from ledger dir to genesis dir.

---

plenum/server/replica.py

Update watermarks in all replicas

---

stp_core/test/helper.py
stp_zmq/test/conftest.py
stp_zmq/test/test_large_messages.py
stp_zmq/test/test_quotas.py
stp_zmq/test/test_zstack.py

Try to make stp tests less texty

---

plenum/server/replica.py
plenum/test/node_catchup/test_node_catchup_when_3_not_primary_node_restarted.py
plenum/test/view_change/test_6th_node_join_after_view_change_by_primary_restart.py
plenum/test/view_change/test_new_node_joins_after_view_change.py
plenum/test/view_change/test_that_domain_ledger_the_same_after_restart_for_all_nodes.py
storage/binary_file_store.py

[INDY-948] Fix ledger restore after restart node

---

plenum/server/replica.py

Update watermark on propagate primary done

---

plenum/common/test_network_setup.py

Fix gen_network script to prevent network settings for client only

---

Jenkinsfile.cd

Build discard property for pipeline build history

---

Jenkinsfile.cd

This reverts commit c8612387a64df06ef71f1e8b44a14d0ed7113edf.

Revert "set build discard property for pipeline build history (#489)"

---

plenum/test/view_change/test_6th_node_join_after_view_change_by_primary_restart.py

[INDY-1084] Fix reconnect in tests while primary stopped

---

plenum/test/view_change/test_6th_node_join_after_view_change_by_primary_restart.py
plenum/test/view_change/test_view_changes_if_master_primary_disconnected.py

[INDY-1084] Unmark test skipping

---

plenum/server/node.py
plenum/test/pool_transactions/helper.py
plenum/test/view_change/test_no_instance_change_before_node_is_ready.py

INDY-1054: do not send InstanceChange if node is not ready yet

---

plenum/common/stack_manager.py

Add new method getNodesServices

---

plenum/common/keygen_utils.py

[INDY-1072] Added comment which public and verkey would be initialized

---

plenum/common/ledger_manager.py

Make ledgerManager use totalNodesCount in quorums

---

stp_core/loop/looper.py

Test of queue processing limits

---

plenum/common/messages/client_request.py
plenum/common/signer_did.py

INDY-582: support empty ('') and None verkey.

---

plenum/server/node.py

[INDY-1150] Hot fix for KeyError exception

---

plenum/test/primary_selection/test_recover_after_demoted.py

INDY-1163: Add a test for recovering after demotion

---

plenum/server/replica.py
plenum/test/checkpoints/test_message_outside_watermark.py
plenum/test/checkpoints/test_watermarks_on_delayed_backup.py

- Backup replica needs to update the watermarks once it gets a quorum of stable checkpoints.

fix restoring of watermarks on delayed backup replica

---

plenum/common/batched.py

Do not make batch if only one msg left

---

plenum/common/ledger_info.py
plenum/common/ledger_manager.py
plenum/server/quorums.py
plenum/test/node_catchup/test_get_last_txn_3PC_key.py
plenum/test/node_catchup/test_same_ledger_initial_catchup.py

fix setting of 3PC key after catch-up

---

ci/ubuntu.dockerfile
setup.py

explicit libindy version [INDY-1170]

---

plenum/server/node.py
plenum/server/replica.py
plenum/test/view_change/test_last_ordered_reset_for_new_view.py

reset last_ordered_3PC for future views during view change.

---

runner.py

Check test suit preparation exit code

---

plenum/common/stack_manager.py

The test for this is contained here https://github.com/hyperledger/indy-node/commit/83837b4ce0c1e7e0a37c584b164505d5f69f34de
Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>

fix KeyError for "services" when pool ledger contains node update txns

---

plenum/common/ledger_manager.py
plenum/test/view_change/test_6th_node_join_after_view_change_by_primary_restart.py

[INDY-1165] Try to decrease testing time

---

plenum/server/replica.py
stp_core/common/log.py

[INDY-1186] Added prefix REPLICA with name for replica logging

---

plenum/server/node.py
plenum/server/pool_manager.py
plenum/server/req_handler.py

[INDY-1138] Added ppTime for stateTsDbStorage

---

Jenkinsfile.cd
setup.py
storage/test/test_leveldb_comparator.py

[WIP] Pipelines for authz branches

---

plenum/persistence/db_hash_store.py

INDY-1205: fallback to leveldb by default for db hash storage.

---

ledger/ledger.py

Use leveldb for the ledger

---

build-scripts/ubuntu-1604/build-3rd-parties.sh

INDY-1205: add maintainer to rocksdb deb package.

---

plenum/test/instances/test_msgs_from_slow_instances.py
plenum/test/primary_selection/test_primary_selection.py

Tests unusual behaviour fix

---

plenum/test/node_catchup/conftest.py
plenum/test/node_catchup/test_node_request_consistency_proof.py

[FIX TESTS] Fix consistency proof query test

---

plenum/test/pool_transactions/test_nodes_data_changed.py

Trying to fix testAddInactiveNodeThenActivate

---

ci/code-validation.dockerfile
ci/ubuntu.dockerfile
setup.py

[Increment libindy-crypto] Bumped libindy-crypto version to 0.4.0

---

setup.py

[Freeze pip] Pip version < 10.0.0

---

scripts/process_logs/process_logs.yml

Log processor: minor fixes

---

LICENSE

* Added Copyright to plenum license

Added Copyright to plenum license

---

scripts/process_logs/README.md
scripts/process_logs/process_logs

Log processor: track COMMIT messages

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
plenum/test/monitoring/test_request_time_tracker.py

INDY-1292: fix base58 version in build scripts

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

[Decrease base58] Decrease base58 to "editable" 0.2.4

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

[INDY-1291] Freeze deps packages version

---

Jenkinsfile.cd

switches pr context to hyperledger

---

build-scripts/ubuntu-1604/build-3rd-parties.sh

[INDY-1291] Remove dublicate orderedset building

---

build-scripts/ubuntu-1604/build-3rd-parties.sh

[FIX 3rd parties] Remove dublicate again

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

[Pygment fix] Bump pygment version and remove version for leveldb

---

plenum/test/primary_selection/test_primary_selection_after_demoted_node_promotion.py
setup.py

[Pygments] bump pegments into setup.py

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

[Pygments] Add patch version for pygments

---

plenum/test/monitoring/test_request_time_tracker.py

Fixed flakiness in test_request_time_tracker

---

plenum/config.py

INDY-1244: set RocksDB as a key-value storage for all.

---

plenum/server/replicas.py
plenum/test/checkpoints/test_message_outside_watermark1.py
plenum/test/instances/test_instance_cannot_become_active_with_less_than_four_servers.py
plenum/test/monitoring/test_warn_unordered_log_msg.py
plenum/test/node_request/test_quorum_f_plus_2_nodes_but_not_primary_off_and_on.py

INDY-1274: log level fix

---

ci/code-validation.dockerfile
ledger/ledger.py
ledger/test/helper.py
plenum/common/script_helper.py
storage/kv_store_rocksdb_int_keys.py
stp_core/common/util.py

[INDY-1289] Added read_only for ledger

---

setup.py

[Bump indy-crypto] Bump indy-crypto and python3-indy

---

scripts/process_logs/process_logs

Log processor: fixed edge case

---

plenum/config.py
plenum/server/notifier_plugin_manager.py
plenum/test/plugin/test_notifier_plugin_manager.py
plenum/test/propagate/test_propagate_recvd_after_request.py

INDY-1251: improve logging of spike detection.

---

plenum/common/ledger_manager.py
plenum/test/node_catchup/test_incorrect_catchup_request.py

Chaqnges:
- added check for end greater then catchupTill in processCatchupReq
- remove check for start greater then leger size in processCatchupReq

INDY-1316:  bug with end greater then catchupTill in processCatchupReq

---

plenum/test/test_request_executed_once_and_without_failing_behind.py

INDY-1319: fix test_request_executed_once_and_without_failing_behind.

---

plenum/server/validator_info_tool.py

[INDY-1175] fix upgrade_log reading

---

plenum/common/stack_manager.py
plenum/test/node_request/test_timestamp/test_3pc_timestamp.py
plenum/test/test_dirty_read.py

Fix tests.

---

ledger/ledger.py

INDY-1319: return get() method back to the ledger implementation.

---

plenum/common/txn_util.py

Fix flake errors

---

plenum/server/config_req_handler.py

INDY-1319: return apply() method to back TestConfigReqHandler class.

---

plenum/client/pool_manager.py

[INDY-1319] Replace txn with txn_data

---

plenum/server/pool_manager.py
stp_core/config.py
stp_zmq/remote.py
stp_zmq/simple_zstack.py
stp_zmq/test/conftest.py
stp_zmq/test/test_zstack.py
stp_zmq/zstack.py

INDY-1332: support different queue sizes for nstack and cstack.

---

plenum/common/test_network_setup.py

INDY-1332: support node/client IPs in test network setup.

---

plenum/common/test_network_setup.py
plenum/common/txn_util.py
plenum/test/script/test_bootstrap_test_node.py
plenum/test/transactions/test_txn_general_access_utils.py

fix missing seq_no in test genesis txns

---

plenum/common/test_network_setup.py

INDY-1332: set 0.0.0.0 for node and client IPs for test network setup.

---

plenum/common/messages/node_messages.py
plenum/test/input_validation/message_validation/test_ledgerstatus_message.py

INDY-1393: Add optional field PROTOCOL_VERSION to LEDGER_STATUS

---

plenum/client/client.py
plenum/test/recorder/test_replay.py
plenum/test/recorder/test_replay_node_bouncing.py

Change expectingAcksFor and expectingRepliesFor maps key from digest to (identifier, reqId)

[INDY-1370]: fix expectingAcksFor and expectingRepliesFor maps key

---

plenum/__metadata__.py

[INDY-1369] Bump minor version for indy-plenum

---

plenum/recorder/replayable_node.py
plenum/recorder/replayer.py
plenum/server/replica.py
plenum/test/recorder/test_replay.py
plenum/test/recorder/test_replay_node_bouncing.py

Signed-off-by: Lovesh Harchandani <lovesh.bond@gmail.com>

change reqId in replayer

---

plenum/config.py
stp_core/config.py

Reduce log rotation backup count

---

plenum/server/replica.py

Adds exception handling for 3pc msgs processing

---

plenum/server/domain_req_handler.py

Fix nym path to make it str

---

plenum/server/node.py
plenum/test/node_request/test_apply_stashed_partially_ordered.py

INDY-1405: Apply stashed batches taking into account that they can be already partially commited

---

plenum/test/node_catchup/test_revert_during_catchup.py

fix for failing test

---

plenum/test/testable.py

[log exception] log if unhandled exception was raised

---

plenum/server/replica.py
plenum/test/replica/test_api.py

Hotfix for node crash

---

plenum/test/testable.py

[Remove tb] remove tb printing in wrap method

---

plenum/common/member/member.py
plenum/common/member/steward.py
plenum/common/test_network_setup.py
plenum/test/script/test_bootstrap_test_node.py
plenum/test/testable.py

use protocolVersion=1 in test genesis files

---

plenum/common/test_network_setup.py
plenum/test/script/test_bootstrap_test_node.py

use protocolVersion=None in test genesis files

---

plenum/server/domain_req_handler.py
plenum/test/req_handler/test_get_value_from_state.py
state/test/trie/test_proof.py
state/trie/pruning_trie.py

RC-1.4.45 with "fix get value from state if there is no BLS multi-sig"

---

plenum/server/domain_req_handler.py
plenum/test/req_handler/test_get_value_from_state.py
state/test/trie/test_proof.py
state/trie/pruning_trie.py

fix get value from state if there is no BLS multi-sig

---

__metadata__.py
plenum/__init__.py
plenum/__metadata__.py
plenum/cli/cli.py
setup.py

Reverts metadata changes from #774 improving metadata routine a bit as well

Fixes and improves metadata routine

---

plenum/__init__.py

Signed-off-by: lovesh harchandani <lovesh.bond@gmail.com>

minor refactor

---

README.md
plenum/config.py

Signed-off-by: Lovesh Harchandani <lovesh.bond@gmail.com>

rename plenum_config.py to indy_config.py

---

plenum/test/instances/test_instance_cannot_become_active_with_less_than_four_servers.py
plenum/test/node_catchup/test_node_request_missing_transactions.py
plenum/test/recorder/test_replay_with_view_change.py
plenum/test/stasher.py
plenum/test/test_stasher.py

fix stasher

---

plenum/common/request.py
plenum/server/replica.py
plenum/test/node_request/test_msg_len_limit_large_enough.py
plenum/test/replica/test_api.py
plenum/test/test_request.py
stp_core/config.py

INDY-1422,1429: Hot fixes

---

plenum/test/node_request/test_quorum_faulty.py
plenum/test/plugin/demo_plugin/test_plugin_request_handling.py
plenum/test/restart/helper.py

fix restart tests to use a correct timeout for check connections

---

plenum/server/monitor.py
plenum/server/replicas.py
plenum/test/plugin/demo_plugin/test_plugin_request_handling.py
plenum/test/restart/helper.py
plenum/test/restart/test_restart_node_4_all.py
plenum/test/restart/test_restart_nodes.py
plenum/test/restart/test_restart_nodes_4_all_wp.py
plenum/test/restart/test_restart_nodes_4_np.py
plenum/test/restart/test_restart_nodes_6_all_np.py
plenum/test/restart/test_restart_nodes_6_all_wp.py
plenum/test/restart/test_restart_nodes_6_np.py
plenum/test/restart/test_restart_nodes_6_wp.py
plenum/test/restart/test_restart_nodes_7.py
plenum/test/restart/test_restart_nodes_7_all.py

Fixes in tests and monitor

---

plenum/server/node.py
plenum/test/view_change/test_client_req_during_view_change.py

INDY-1453: do not process client reqs during View Change

---

plenum/common/ledger_manager.py
plenum/config.py
plenum/server/node.py
plenum/test/node_catchup/test_build_ledger_status.py
plenum/test/node_catchup/test_same_ledger_initial_catchup.py
plenum/test/node_catchup/test_update_txn_seq_range_after_catchup.py
plenum/test/node_request/test_quorum_f_plus_2_nodes_including_primary_off_and_on.py
plenum/test/test_node.py

INDY-1452: store seqNo-3PCKey map for ledgers after catchup

---

plenum/server/view_change/view_changer.py
plenum/test/test_node.py
plenum/test/view_change/test_no_future_view_change_while_view_change.py

INDY-1458: do not start propagate primary if view change is in progress

---

plenum/test/view_change_with_delays/test_delayed_instance_changes.py

add test for delayed IC and VCD during view change

---

plenum/server/node.py
plenum/test/view_change/test_view_change_can_finish_despite_perpetual_catchup.py

INDY-1454: Fix perpetual catchup during view change

---

plenum/server/replica.py
plenum/server/replicas.py

Extend logging with checkpoint send

---

plenum/server/node.py
plenum/test/helper.py
plenum/test/view_change/test_disable_view_change.py
plenum/test/view_change/test_view_change_start_without_primary.py
plenum/test/view_change/test_view_change_timeout.py
plenum/test/view_change/test_view_change_timeout_reset.py
plenum/test/view_change_with_delays/test_two_view_changes_with_delay_on_one_node.py
plenum/test/view_change_with_delays/test_two_view_changes_with_delayed_commits.py
plenum/test/view_change_with_delays/test_two_view_changes_with_propagate_primary_on_one_delayed_node.py
plenum/test/view_change_with_delays/test_view_change_with_advancing_node.py
plenum/test/view_change_with_delays/test_view_change_with_delay_on_one_node.py
plenum/test/view_change_with_delays/test_view_change_with_delayed_commits.py
plenum/test/view_change_with_delays/test_view_change_with_propagate_primary_on_one_delayed_node.py
plenum/test/view_change_with_delays/test_view_change_with_unaligned_prepare_certificates_on_half_nodes.py
plenum/test/view_change_with_delays/test_view_change_with_unaligned_prepare_certificates_on_one_node.py

INDY-1454: Reset timeout when starting consecutive view change

---

plenum/test/pool_transactions/test_nodes_ha_change_back.py

Trying to fix some flaky tests

---

stp_core/config.py

New stack sizes: clien 3k, node 20k

---

plenum/test/view_change/test_view_change_timeout.py

INDY-1484: Fix flaky test

---

plenum/test/restart/test_restart_nodes_6_np.py
plenum/test/restart/test_restart_nodes_6_wp.py
plenum/test/restart/test_restart_nodes_7.py

INDY-1487: Fix flaky tests

---

plenum/__metadata__.py

[Bump version] bump version to 1.5

---

plenum/server/view_change/view_changer.py
plenum/test/view_change/conftest.py
plenum/test/view_change/test_instance_change_from_unknown.py

[INDY-1470] Add fix for received instance_change from unknown node

---

stp_core/common/logging/CompressingFileHandler.py

INDY-1502: Improve log rotation logic

---

plenum/common/util.py

Add get_utc_datetime utility

---

plenum/server/node.py

INDY-1507: Fix rare failure case

---

plenum/server/node.py

INDY-1477: fix discard calling if node is blacklisted.

---

plenum/common/exceptions.py
plenum/server/message_handlers.py
plenum/server/message_req_processor.py
plenum/test/node_catchup/test_node_catchup_with_new_ls_form.py
plenum/test/node_request/message_request/test_valid_message_request.py

- Added an integration test verifying catch-up in case one of nodes sends MessageReps with LedgerStatuses in outdated format.
- Added unit tests for some unhandled cases in message request / response handling logic.
- Added handling for these cases to message request / response processing logic.

INDY-1519: Fixed handling of message replies

---

plenum/server/monitor.py

[INDY-1468] Fix metrics displaying

---

plenum/common/metrics_stats.py
plenum/test/test_metrics_collector.py
plenum/test/test_metrics_stats.py
stp_zmq/zstack.py

INDY-1475: Implement calculating metrics dynamics

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
plenum/server/validator_info_tool.py
plenum/test/validator_info/test_validator_info.py
setup.py

Changes:
- add committed and uncommitted root hashes for state
- add memory profiler
- fix HDD usage for node
- move extractions to general_info section
- limit uncommitted txns count

[INDY-1542] Validator additionals

---

plenum/config.py
stp_core/config.py

INDY-1549: Change default settings for better performance and stability

---

ci/ubuntu.dockerfile
setup.py

Plenum 683

---

plenum/common/metrics_stats.py

INDY-1543: Fix crash in get_metrics

---

scripts/process_logs/README.md
scripts/process_logs/process_logs

Log processor improvements

---

plenum/server/node.py

Signed-off-by: lovesh harchandani <lovesh.bond@gmail.com>

get request handler by txn type

---

plenum/config.py
plenum/server/node.py

INDY-1543: Make metrics flush interval configurable

---

plenum/server/replica.py

INDY-1583: Removal of check for pre-prepare

---

plenum/server/node.py
plenum/test/view_change/test_client_req_during_view_change.py

unpackClientMsg() can receive message in different types (dict, Request, SafeRequest). Added changing message to a dict type and changed way to response Nack to client.

INDY-1564: Fix problem with incorrect Nack response message.

---

plenum/server/validator_info_tool.py

Remove memory profiler from default validator info params

---

crypto/bls/indy_crypto/bls_crypto_indy_crypto.py
plenum/common/keygen_utils.py

Changes:
- add bls key proof output to console 
- add method for generating key proof

INDY-1588: Add method for generating key proof

---

plenum/server/validator_info_tool.py

Rename properties to make them public

---

plenum/common/metrics_collector.py
plenum/server/node.py

INDY-1602: Add more metrics, remove some

---

Jenkinsfile.ci

Update Jenkins CI config

---

plenum/server/monitor.py

Minor fix in monitor

---

plenum/server/monitor.py
plenum/test/monitoring/test_request_time_tracker.py

INDY-1659: Improve performance of monitor

---

plenum/server/client_authn.py
plenum/test/client/test_core_authn.py

Signed-off-by: lovesh harchandani <lovesh.bond@gmail.com>

accept threshold param in authenticate

---

plenum/server/node.py
plenum/test/plugin/test_hooks.py

We assuming that reply must be hooked:
- On reply on write request
- On reply on write already written request
- On reply on get txn request

INDY-1673: Changes to reply pre_send hook.

---

plenum/server/node.py
plenum/server/pool_manager.py

- Added logging of state to node initialization.
- Added logging of state to catch-up.

INDY-1657: Enhanced logging of state changes

---

plenum/common/metrics_collector.py
plenum/server/monitor.py
plenum/server/node.py
plenum/server/propagator.py

INDY-1602: Add more metrics

---

plenum/server/node.py

INDY-1649: do not re-verify signature for Propagates.

---

plenum/server/node.py

[INDY-1649] fix verified_reqs cleaning

---

plenum/server/monitor.py

INDY-1688: Fix requests tracking in monitor

---

plenum/server/node.py

[INDY-1649] clean verified reqs only for instance of ReqAuthenticator

---

scripts/process_logs/process_logs

- Added missed values to "level" matcher in process_logs script.

Corrected level matcher in process_logs

---

plenum/common/ledger_manager.py
plenum/test/node_catchup/test_process_catchup_replies.py

Changed a recursion in _processCatchupReplies to a cycle.

INDY-1711: Bugfix in  LedgerManager._processCatchupReplies

---

plenum/test/propagate/test_propagate_recvd_after_request.py
plenum/test/propagate/test_propagate_recvd_before_request.py

[INDY-1649] Checnge tests for checking auth call count

---

plenum/common/metrics_collector.py
plenum/config.py
plenum/test/metrics/helper.py
plenum/test/metrics/test_metrics_collector.py
plenum/test/metrics/test_metrics_stats.py

Reduce frequency of writes into metrics_db

---

ci/ubuntu.dockerfile
setup.py

[bump indy-crypto] bump version for python3-indy-crypto

---

plenum/config.py
plenum/server/validator_info_tool.py

INDY-1723: Profiling on node objects 

---

plenum/config.py

Validator info dump time revert

---

plenum/common/metrics_collector.py
plenum/server/node.py

INDY-1775: add CONNECTED_CLIENTS_NUM metric.

---

plenum/common/monitor_strategies.py
plenum/test/monitoring/test_acc_monitor_strategy.py

Add logs to accumulating monitor strategy

---

storage/kv_store_file.py

Remove ret val declaration

---

plenum/test/view_change/test_prepare_in_queue_before_vc.py
plenum/test/view_change/test_vc_start_msg_strategy.py

[INDY-1687] small changes in tests

---

plenum/config.py
plenum/test/primary_selection/test_primary_selector.py
plenum/test/view_change/conftest.py

[INDY-1835] Enable PreViewChange strategy

---

plenum/server/node.py
plenum/test/input_validation/test_handle_one_node_message.py

[INDY-1849] fix for each message serialization during batch handling

---

ci/ubuntu.dockerfile
setup.py

use latest stable libindy

---

plenum/test/metrics/test_metrics_config.py

Fix rare flakiness of test_metrics_config

---

plenum/common/value_accumulator.py
plenum/test/metrics/helper.py
plenum/test/metrics/test_metrics_collector.py

Improve measure_time metrics tests

---

plenum/common/test_network_setup.py

INDY-1770: decrease clients connections limit.

---

plenum/common/ledger_manager.py
plenum/common/metrics_collector.py
plenum/server/node.py
plenum/test/metrics/test_metrics_config.py

Add more metrics

---

plenum/test/checkpoints/test_checkpoint_bounds_after_catchup.py
plenum/test/checkpoints/test_ordering_after_catchup.py
plenum/test/conftest.py
plenum/test/primary_selection/test_add_node_to_pool_with_large_ppseqno.py
plenum/test/primary_selection/test_primary_selection_pool_txn.py
plenum/test/script/helper.py
plenum/test/script/test_change_non_primary_node_ha.py
plenum/test/script/test_change_primary_node_ha.py
plenum/test/view_change/test_6th_node_join_after_view_change_by_primary_restart.py

Old client's lump removal

---

plenum/common/test_network_setup.py

Client removal fixes

---

plenum/server/node.py

INDY-1836: fix removing of entries from requests queue.

---

plenum/server/node.py

INDY-1856: Fix validator info init

---

docs/misc/zeromq_features.md

INDY-1902: add a doc with known ZMQ features.

---

plenum/config.py
plenum/server/models.py
plenum/server/view_change/view_changer.py
plenum/test/helper.py
plenum/test/metrics/helper.py
plenum/test/metrics/test_metrics_collector.py
plenum/test/metrics/test_metrics_stats.py
plenum/test/server/test_models.py
plenum/test/view_change/test_instance_change_from_unknown.py
plenum/test/view_change/test_old_instance_change_discarding.py
plenum/test/view_change/test_prepare_in_queue_before_vc.py
plenum/test/view_change/test_view_change_happens_post_timeout.py
plenum/test/view_change_with_delays/test_view_change_with_different_prepare_certificate.py

Accumulated INSTANCE_CHANGE messages should be discarded based on some configurable timeout

INDY-1909: add discarding of old instance change messages 

---

plenum/server/replicas.py

INDY-1926: add check for None of replica's primary name during logging.

---

docs/start_nodes.md

INDY-1925: Fixes for documentation

---

plenum/server/node.py
plenum/server/propagator.py

INDY-1836: add force_free() method for Requests.

---

plenum/test/metrics/test_metrics_collector.py
plenum/test/restart/test_restart_node_4_all.py
plenum/test/restart/test_restart_nodes.py
plenum/test/restart/test_restart_nodes_4_all_wp.py
plenum/test/restart/test_restart_nodes_6_all_np.py
plenum/test/restart/test_restart_nodes_6_all_wp.py
plenum/test/restart/test_restart_nodes_7_all.py

Fix intermittent tests by increasing timeouts

---

setup.py

[pytest] pin pytest-asyncio version to 0.8.0

---

design/catchup-and-audit-proposal.md

INDY-1924: Add options concerning BLS multisigs

---

plenum/config.py
plenum/server/validator_info_tool.py
plenum/test/validator_info/test_upgrade_log.py

INDY-1922: Fix and tests for crop upgrade log

---

plenum/server/batch_handlers/batch_request_handler.py
plenum/server/request_handlers/handler_interfaces/request_handler.py
plenum/server/request_handlers/node_handler.py
plenum/test/req_handler/test_node_handler.py

INDY-1858: Fix in node_handler and tests

---

plenum/server/replica.py
plenum/test/replica/test_api.py

INDY-1949: Modify logging, remove redundant validation

---

plenum/test/node_request/test_commit/test_commits_dequeue_commits.py

Tests for PR: https://github.com/hyperledger/indy-plenum/pull/1065

Add test_dequeue_and_validate_commits

---

plenum/config.py
plenum/server/propagator.py
plenum/server/replica.py
plenum/test/malicious_behaviors_node.py
plenum/test/node_request/test_propagate/helper.py
plenum/test/node_request/test_propagate/test_node_lacks_finalised_requests.py
plenum/test/node_request/test_propagate/test_node_request_only_needed_propagates.py
plenum/test/node_request/test_propagate/test_node_request_propagates_with_delay.py
plenum/test/replica/test_replica_received_preprepare_with_unknown_request.py
plenum/test/test_node.py

INDY-1965: Delay propagate request. Optimization.

---

plenum/server/replica.py
plenum/test/helper.py

INDY-1965: Logging changes

---

plenum/server/view_change/pre_view_change_strategies.py
plenum/server/view_change/view_changer.py
plenum/test/restart/test_restart_node_with_view_changes.py

INDY-1966: add on_strategy_complete to VCStartMsgStrategy

---

plenum/test/util/test_common_util.py

INDY-1754: add test_random_string for randomString

---

plenum/server/view_change/view_changer.py
plenum/test/freshness/test_view_change_happens_if_primary_is_slow_to_update_freshness.py

INDY-1911: Make acceptable freshness interval configurable

---

build-scripts/ubuntu-1604/Dockerfile

Fixes fpm installation for build env

---

plenum/test/pool_transactions/test_txn_pool_manager.py

Refactoring test_twice_demoted_node_dont_write_txns

---

plenum/server/node.py

[INDY-2001] move write_req_validator into node init

---

plenum/server/validator_info_tool.py
plenum/test/validator_info/test_validator_info.py
plenum/test/validator_info/test_validator_info_vc.py

INDY-2008: Fix a problem with view change and add audit ledger in validator-info

---

plenum/common/messages/fields.py

INDY-2003: add parameter can_be_empty in LimitedLengthStringField

---

Jenkinsfile.cd

Set fixed version of jenkins shared library for CD pipeline

---

plenum/test/pool_transactions/helper.py

[INDY-2006] add no_wait option for sdk_add_new_nym

---

plenum/common/channel.py
plenum/server/catchup/catchup_rep_gatherer.py
plenum/server/catchup/seeder_service.py

INDY-1945: Extract routing from RxChannel

---

plenum/common/messages/node_messages.py
plenum/server/replica.py
plenum/server/suspicion_codes.py
plenum/test/helper.py
plenum/test/input_validation/message_validation/test_prepare_message.py
plenum/test/malicious_behaviors_node.py
plenum/test/node_request/message_request/test_preprepare_request.py
plenum/test/replica/conftest.py
plenum/test/replica/helper.py
plenum/test/replica/test_process_prepare.py
plenum/test/replica/test_process_preprepare.py

INDY-1944: Сheck audit txn root when validating prepare

---

plenum/server/pool_req_handler.py
plenum/server/request_handlers/node_handler.py
plenum/test/pool_transactions/test_nodes_with_pool_txns.py
plenum/test/req_handler/test_node_handler.py

[INDY-2003] remove isSteward from modern reg_handlers

---

plenum/server/domain_req_handler.py
plenum/server/ledger_req_handler.py
plenum/test/bls/test_no_state_proof.py
plenum/test/bls/test_state_proof.py

INDY-2010: fix a reply format for domain transactions

---

plenum/server/catchup/catchup_rep_service.py
plenum/server/catchup/cons_proof_service.py
plenum/server/catchup/ledger_leecher_service.py
plenum/server/catchup/node_leecher_service.py
plenum/server/catchup/utils.py
plenum/server/node.py
plenum/server/validator_info_tool.py
plenum/test/node_catchup/test_build_ledger_status.py
plenum/test/node_catchup/test_ledger_info.py
plenum/test/node_catchup/test_node_catchup_after_restart_after_txns.py
plenum/test/node_catchup/test_node_request_consistency_proof.py
plenum/test/node_catchup/test_process_catchup_replies.py
plenum/test/node_catchup_with_3pc/test_slow_catchup_while_ordering.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_only_checkpoints.py

INDY-1945: Fix catchup logic to use audit ledger

---

plenum/server/catchup/node_leecher_service.py
plenum/server/catchup/seeder_service.py

INDY-1993: Hotfix for crash in generating consistency proof

---

plenum/server/catchup/catchup_rep_service.py
plenum/server/catchup/cons_proof_service.py
plenum/server/catchup/node_leecher_service.py

Catchup log messages improvements

---

plenum/server/catchup/catchup_rep_service.py
plenum/server/catchup/ledger_leecher_service.py

INDY-1993: Move catchup start notification before consistency proof gathering

---

plenum/common/ledger_uncommitted_tracker.py
plenum/server/batch_handlers/audit_batch_handler.py
plenum/test/tracker/test_ledger_uncommitted_tracker.py

[ST-513] add txn_root into LedgerUncommittedTracker

---

plenum/common/ledger.py
plenum/server/batch_handlers/audit_batch_handler.py
plenum/server/node.py
plenum/test/audit_ledger/conftest.py
plenum/test/audit_ledger/test_audit_ledger_handler_catchup.py
plenum/test/ledger/test_ledger_discard_txns.py

INDY-1993: improve logging; correctly set last committed after catchup of audit

---

ledger/ledger.py
plenum/common/ledger.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/helper.py
plenum/test/stasher.py
plenum/test/view_change_with_delays/test_view_change_during_unstash.py

INDY-1993: Catchup tests

---

plenum/server/node.py
plenum/test/freshness/test_freshness_batch_updates_last_ordered.py

INDY-2022: Review fixes

---

plenum/server/replica.py
plenum/test/replica/test_revert_from_malicious.py
storage/optimistic_kv_store.py

[Malicious_primary] fix count of request for reverting

---

plenum/server/node.py
plenum/server/view_change/view_changer.py

INDY-1946: Fix for replicas inconsistency

---

plenum/server/node.py
plenum/test/node/test_api.py

ST-541 Add flag to disable seqNoDB update during catchup

---

plenum/common/constants.py
plenum/server/node.py

ST-528: add the POST_NODE_STOPPED hook

---

ci/ubuntu.dockerfile
setup.py

bump libindy

---

plenum/server/node.py
plenum/test/req_handler/test_unregister_req_handler.py

[ST-520] add unregister_req_handler method with unit tests

---

plenum/server/replica.py
plenum/test/replica/test_api.py

INDY-2050: remove LogicError from  __is_next_pre_prepare

---

plenum/server/replica.py
plenum/test/common/test_replicas_suspicious.py
plenum/test/node_request/test_pre_prepare/test_pp_obsolescence_check_fail_for_delayed.py

INDY-2046: View change only on master malicious

---

plenum/common/messages/fields.py

INDY-2043: change LimitedLengthStringField format

---

plenum/server/propagator.py

INDY-2051: Payload digest fix

---

plenum/server/node.py
plenum/test/node_catchup/test_post_genesis_txn_from_catchup_added_to_ledger.py

Fix crash when catching up genesis txns

---

plenum/test/helper.py

ST-549 Fix Request for requests without identifier

---

plenum/server/catchup/seeder_service.py

INDY-2053: Improve catchup logging

---

plenum/server/config_req_handler.py
plenum/test/input_validation/test_client_taa_op.py

INDY-2066: Refactor and add tests

---

plenum/test/txn_author_agreement/helper.py
plenum/test/txn_author_agreement/test_txn_author_agreement.py

INDY-2066: Improve tests

---

plenum/test/helper.py

ST-557 Add taaAcceptance field to Request builder

---

plenum/server/last_sent_pp_store_helper.py
plenum/server/replica_validator.py

Reduce amount of logged information

---

plenum/server/node.py
plenum/test/view_change/test_client_req_during_view_change_integration.py

INDY-2122: Don't send NACK for requests discarded during view change

---

plenum/server/node.py
plenum/server/primary_selector.py
plenum/test/audit_ledger/test_demote_backup_primary.py
plenum/test/audit_ledger/test_demote_backup_primary_without_view_change.py

INDY-2129: Fix the problem with demoting a backup primary node

---

ci/ubuntu.dockerfile
setup.py

INDY-2087: bump libindy version

---

plenum/server/request_handlers/handler_interfaces/write_request_handler.py
plenum/server/request_handlers/node_handler.py
plenum/server/request_handlers/nym_handler.py
plenum/server/request_handlers/txn_author_agreement_aml_handler.py
plenum/server/request_handlers/txn_author_agreement_handler.py
plenum/server/request_managers/write_request_manager.py
plenum/test/buy_handler.py

ST-510 Add request param for write request handler

---

ci/ubuntu.dockerfile
plenum/test/txn_author_agreement/test_get_empty_txn_author_agreement.py
plenum/test/txn_author_agreement/test_get_taa_aml.py
plenum/test/txn_author_agreement/test_get_txn_author_agreement.py
plenum/test/txn_author_agreement/test_txn_author_agreement.py
setup.py

INDY-2098: Improve tests for TAA state proofs

---

plenum/test/common/test_batch_handler.py
plenum/test/common/test_database_manager.py
plenum/test/test_batch_handler.py

INDY-2108: More tests for pluggable request handlers

---

plenum/server/node.py
plenum/server/node_bootstrap.py
plenum/test/test_node.py

[INDY-1860] move init to separate helper class

---

plenum/server/database_manager.py
plenum/server/request_managers/request_manager.py

ST-523: Fix for plugins integration

---

plenum/server/request_handlers/audit_handler.py

INDY-2153 Fix external audit requests

---

plenum/test/requests/test_send_audit_txn.py

Test for audit txn sending

---

ci/ubuntu.dockerfile
plenum/test/req_handler/test_node_handler.py

[INDY-2163] move to new docker images with changed gpg keys

---

Jenkinsfile.cd

[BUMP] bump jenkins shared to 2.2.1

---

plenum/server/request_managers/write_request_manager.py
plenum/test/txn_author_agreement/acceptance/test_taa_acceptance_validation.py

INDY-2157: change the reject message for a too precise TAA time in requests

---

plenum/common/stashing_router.py
plenum/config.py
plenum/server/consensus/view_change_service.py
plenum/test/test_stashing_queue.py
plenum/test/test_stashing_router.py

INDY-2147: Improve StashingRouter

---

plenum/common/messages/node_messages.py
plenum/common/types.py
plenum/server/consensus/consensus_data_provider.py
plenum/server/consensus/replica_service.py
plenum/server/consensus/view_change_service.py
plenum/test/consensus/conftest.py
plenum/test/consensus/helper.py
plenum/test/consensus/test_sim_view_change.py
plenum/test/consensus/test_view_change_service.py
plenum/test/simulation/sim_random.py
plenum/test/simulation/test_sim_random.py

INDY-2147: Implement PBFT view change

---

plenum/server/consensus/consensus_data_provider.py
plenum/server/consensus/consensus_shared_data.py
plenum/server/consensus/view_change_service.py
plenum/test/consensus/helper.py
plenum/test/consensus/test_sim_view_change.py
plenum/test/consensus/test_view_change_service.py

- fixed math implementation of PBFT View Change
- extended tests to check that all committed requests from previous view will be committed in a New View (one of the main criteria of data consistency)

INDY-2147: Fixes in PBFT View Change Math

---

plenum/server/catchup/cons_proof_service.py
plenum/test/node_catchup/test_catchup_reasking.py

INDY-2112: make reask_ledger_status() and _reask_last_cons_proof() repeatable

---

ci/ubuntu.dockerfile
setup.py

Bump libindy 1167

---

stp_zmq/client_message_provider.py
stp_zmq/test/test_stashed_client_messages.py

Fix for provider

---

ci/ubuntu.dockerfile
plenum/test/txn_author_agreement/acceptance/test_taa_acceptance_integration_validation.py
setup.py

INDY-2157: bump sdk version, add a TAA integration test

---

ci/ubuntu.dockerfile
setup.py

INDY-2157: bump libindy version

---

plenum/server/client_authn.py
plenum/server/request_handlers/utils.py
plenum/test/signing/test_create_did_without_endorser.py
plenum/test/signing/test_signing_out_of_ledger.py

INDY-2171: Signature verification changes

---

ci/ubuntu.dockerfile
setup.py

INDY-2162: bump libindy

---

plenum/server/consensus/checkpoint_service.py
plenum/server/consensus/consensus_shared_data.py
plenum/server/consensus/view_change_service.py
plenum/server/replica.py
plenum/test/consensus/checkpoint_service/test_checkpoint_service_unit.py
plenum/test/consensus/view_change/helper.py
plenum/test/consensus/view_change/test_view_change_msg_creation.py
plenum/test/replica/test_consensus_data_helper.py

INDY-1335: use BatchID instead of PrePrepares in consensus shared data

---

stp_zmq/client_message_provider.py

Change a log level for messages from the ClientMessageProvider

---

plenum/test/zstack_tests/test_restart_client_stack.py
stp_core/config.py
stp_zmq/zstack.py

Increase ZMQ bind retry timeout

---

CODEOWNERS

Modify Codeowners list

---

plenum/common/exceptions.py
plenum/common/util.py
plenum/server/client_authn.py
plenum/test/blacklist/test_blacklist_client.py
plenum/test/client/test_client.py
plenum/test/common/test_digest_validation.py
plenum/test/helper.py
plenum/test/node_request/test_reply_from_ledger_for_request.py
plenum/test/signing/test_create_did_without_endorser.py
plenum/test/signing/test_signing.py
plenum/test/util/test_common_util.py

Change the formatting of exceptions for the client

---

plenum/server/ledgers_bootstrap.py
plenum/server/node.py
plenum/test/observer/test_observer_node_each_batch.py
plenum/test/pool_transactions/test_on_pool_membership_changes.py
state/pruning_state.py
state/state.py

SN-7: move init states from ledger after Node initialization

---

storage/kv_in_memory.py

SN-7: fix KeyValueStorageInMemory

---

plenum/test/checkpoints/test_checkpoints_removal_after_catchup.py
plenum/test/checkpoints/test_checkpoints_removal_after_catchup_during_view_change.py

[INDY-2177] ToDo in tests

---

plenum/server/consensus/ordering_service.py
plenum/test/consensus/order_service/test_sim_order_during_view_change.py

[INDY-2223] Fix reordering after view_change

---

stp_zmq/zstack.py

INDY-2222 -- improve logging

---

plenum/common/batched.py

INDY-2172: Changed the log level for removed RIDs

---

stp_zmq/zstack.py

INDY-2222 -- Add some more logs

---

plenum/server/consensus/ordering_service.py
plenum/server/consensus/view_change_service.py
plenum/server/node.py
plenum/test/view_change_service/test_view_change_triggered.py
stp_zmq/zstack.py

INDY-2223: Fix test_view_change_with_next_primary_stopped

---

setup.py

[INDY-2213]: Bump pyzmq version

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
build-scripts/ubuntu-1604/build-indy-plenum.sh
setup.py

[INDY-2213]: Fix FPM dependencies

---

plenum/server/consensus/ordering_service_msg_validator.py
plenum/server/node.py
plenum/test/consensus/message_req/message_req_3pc_service/test_incorrect_message_req_processing.py
plenum/test/consensus/order_service/test_ordering_msg_validator.py
plenum/test/node/test_api.py

INDY-2248: add a message validation for instance id

---

plenum/server/consensus/primary_selector.py
plenum/server/consensus/view_change_service.py
plenum/server/node.py

Change logging for select primary

---

Jenkinsfile.cd

[INDY-2213]: Update pyzmq for Jenkins CD

---

plenum/server/consensus/view_change_service.py
plenum/server/suspicion_codes.py
plenum/test/primary_selection/test_promotion_before_view_change.py

INDY-2247: propose view change if a new primary is same with a previous one

---

stp_zmq/zstack.py

- do not send ping/pong msgs in Batches 
- revert not sending Batches to disconnected

Indy 2261: do not send ping/pong msgs in Batches 

---

plenum/server/consensus/ordering_service.py
plenum/test/audit_ledger/test_audit_ledger_handler.py
plenum/test/node_catchup_with_3pc/test_preprepares_and_prepares_recovery_after_catchup.py
plenum/test/view_change_with_delays/helper.py
plenum/test/view_change_with_delays/test_view_change_with_delayed_commits_on_all_but_one_node_and_restart_of_those_nodes.py
plenum/test/view_change_with_delays/test_view_change_with_delayed_commits_on_half_of_the_nodes_and_restart_of_that_half.py
plenum/test/view_change_with_delays/test_view_change_with_delayed_commits_on_half_of_the_nodes_and_restart_of_the_other_half.py

- integration tests improvements
- small code changes
- unit tests changes

[INDY-2235]: Improving tests

---

plenum/config.py
plenum/test/conftest.py
plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/node_catchup/test_node_catchup_after_restart_after_txns.py
plenum/test/node_request/message_request/test_node_requests_missing_preprepares_prepares_and_commits.py
plenum/test/node_request/test_discard_3pc_for_ordered.py
plenum/test/node_request/test_propagate/test_node_lacks_finalised_requests.py
plenum/test/node_request/test_timestamp/test_3pc_timestamp.py

increment Max3PCBatchWait for better stability and performance

INDY-2268: increment Max3PCBatchWait

---

plenum/common/messages/internal_messages.py
plenum/common/messages/node_messages.py
plenum/server/consensus/checkpoint_service.py
plenum/server/consensus/ordering_service.py
plenum/server/consensus/primary_selector.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/batching_3pc/catch-up/test_freeing_forwarded_preprepared_request.py
plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/replica/helper.py
plenum/test/replica/stashing/test_replica_unstashing.py

[INDY-2267] remove primaryChange and simplify catchup_complete logic

---

plenum/server/request_managers/write_request_manager.py

INDY-2292: fix restore_state() in WriteRequestManager

---

plenum/server/consensus/view_change_service.py
plenum/server/replica.py

INDY-2263: Make ViewChangeService unsubscribe from messages on cleanup

---

plenum/server/consensus/ordering_service.py
plenum/test/audit_ledger/test_node_reg_in_ordered.py

INDY-2262: fix restoring node reg for Ordered if it's not in audit ledger yet

---

plenum/server/request_managers/write_request_manager.py
plenum/test/req_handler/test_request_manager.py

INDY-2292: add more tests for a state restoring

---

plenum/server/batch_handlers/audit_batch_handler.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/audit_ledger/test_do_not_select_primaries_from_audit_on_startup.py
plenum/test/checkpoints/helper.py
plenum/test/primary_selection/test_recover_more_than_f_failure.py
plenum/test/replica/stashing/test_replica_unstashing.py

- do not restore primaries from the audit ledger but select them in a common way
- some cleanups

INDY-2298: do not restore primaries from the audit ledger 

---

plenum/server/batch_handlers/audit_batch_handler.py
plenum/server/batch_handlers/three_pc_batch.py
plenum/test/audit_ledger/helper.py
plenum/test/audit_ledger/test_audit_ledger_handler.py
plenum/test/audit_ledger/test_audit_ledger_with_node_reg_feature_added.py

fix filling node reg in audit ledger the first time node reg is introduced for an existing audit ledger

INDY-2262: fix filling node reg in audit ledger

---

plenum/server/batch_handlers/node_reg_handler.py
plenum/test/audit_ledger/test_audit_multiple_uncommitted_node_regs.py
plenum/test/helper.py
plenum/test/node_reg_handler/test_node_reg_handler.py

fix node reg in audit ledger when there are multiple uncomitted NODE txns changing the node reg

INDY-2262: fix node reg in audit ledger 

---

plenum/server/node.py

Fix passing connections to services

---

plenum/server/request_handlers/node_handler.py
plenum/test/pool_transactions/test_nodes_data_changed.py

[INDY-2024] remove steward-only check for NODE txns

---

docs/source/transaction_author_agreement.md

INDY-2302/2313: Update Transaction Author Agreement documentation

---

Jenkinsfile.ci

[CI] increase timeout for CI

---

plenum/server/request_handlers/txn_author_agreement_handler.py
plenum/test/txn_author_agreement/helper.py
plenum/test/txn_author_agreement/test_get_txn_author_agreement.py

INDY-2316: bugfix in update_state for txn_author_agreement_handler

---

plenum/server/txn_version_controller.py
plenum/test/txn_author_agreement/test_get_txn_author_agreement.py

INDY-2316: fix for getting txn version for a state recovering

---

plenum/server/request_handlers/base_taa_handler.py
plenum/server/request_handlers/txn_author_agreement_disable_handler.py
plenum/server/request_handlers/txn_author_agreement_handler.py
plenum/test/txn_author_agreement/test_config_req_handler_taa_utils.py
plenum/test/txn_author_agreement/test_txn_author_agreement_disable.py

INDY-2316: disable only active TAAs

---

plenum/server/request_handlers/txn_author_agreement_disable_handler.py

INDY-2316: fix TxnAuthorAgreementDisableHandler

---

plenum/server/request_handlers/txn_author_agreement_handler.py
plenum/test/conftest.py
plenum/test/freshness/test_replica_freshness.py
plenum/test/replica_removing/helper.py
plenum/test/req_handler/test_txn_author_agreement_handler.py
plenum/test/txn_author_agreement/test_get_txn_author_agreement.py
plenum/test/txn_author_agreement/test_txn_author_agreement.py
plenum/test/txn_author_agreement/test_txn_author_agreement_disable.py

INDY-2316: Improve integration tests, fix unretirement edge case

---

ci/ubuntu.dockerfile
plenum/test/txn_author_agreement/helper.py
setup.py

INDY-2316: bump libindy version, use taa request builder from libindy

---

plenum/test/consensus/view_change/test_sim_view_change.py

Add test_view_change_permutations

---

plenum/common/ledger.py
plenum/server/consensus/ordering_service.py

[INDY-2324] Get back requests from PrePrepare

---

plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/demotion_promotion/test_demote_promote.py

[INDY-2326] Add test for restarting only after promotion

---

common/error_handling.py

[ERROR_HANDLING] add module with examples for Exception handling

---

docs/source/error_handling.md

[ERROR HANDLING] Document error handling strategies

---

plenum/common/exceptions.py

fix InvalidClientMessageException str representation

---

plenum/common/exceptions.py

Change a string format for InvalidClientMessageException

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>

Fix CVE-2019-18874

---

dev-setup/ubuntu/ubuntu-2004/SetupVMTest.md
stp_core/loop/looper.py

Signed-off-by: Ryan Marsh <ryan.marsh44@gmail.com>

WIP:  Ubuntu 20.04 VM setup

---

Jenkinsfile.ci
ci/ubuntu.dockerfile
setup.py

Signed-off-by: anton.denishchenko <anton.denishchenko@dsr-corporation.com>

Bump libindy ver 1.15.0~1618

---

.github/settings.yml

Signed-off-by: Ry Jones <ry@linux.com>

Add settings file.

---

.github/workflows/build/Dockerfile

Signed-off-by: Anton Denishchenko <anton.denishchenko@evernym.com>

Bump libindy ver 1.15.0~1625 for GitHub-Actions

---

.github/workflows/build.yaml

added skip upload of python package to pypi package if already exists

---

.github/workflows/build/Dockerfile
ci/ubuntu.dockerfile
setup.py

bump indy-sdk to v. 1.16.0

---

README.md

Signed-off-by: Philipp Schlarb <p.schlarb@esatus.com>

fixed typo in gitpodlink

---

.gitpod.yml

Signed-off-by: pSchlarb <p.schlarb@esatus.com>

removed pip legacy resolver in gitpod.yml due to being deprecated

---

.vscode/settings.json

Signed-off-by: pSchlarb <p.schlarb@esatus.com>

Enforce LF for VScode

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/tag.yaml

https://github.com/hyperledger/indy-shared-gha/issues/8 needs to be done first.

Pinned indy-shared-gha reference

---

docs/source/ci-cd.md
docs/source/index.rst

Fixes : #1591
Signed-off-by: Philipp Schlarb <p.schlarb@esatus.com>

Added CICD Documentation reference

---

.github/workflows/PR.yaml
.github/workflows/releasepr.yaml

- Fix error in releasepr.yaml
- Ensure the triggers on PR.yaml and releasepr.yaml are mutually exclusive.

Adjust workflow triggers.

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/tag.yaml

Signed-off-by: Philipp Schlarb <p.schlarb@esatus.com>

fixed GHA variable format errors

---

.github/workflows/publishRelease.yaml

Fix missing component in publish release workflow.

---

Jenkinsfile.cd

- SovrinHelpers v2.2.3 includes an update to fix dependency issues in `code-validation.dockerfile` affecting the CD pipeline.

Upgrade to SovrinHelpers v2.2.3

---

build-scripts/ubuntu-1604/Dockerfile

Pin pip to ensure expected defaults are observed.

---

.devcontainer/Dockerfile
.github/workflows/build/Dockerfile.ubuntu-2004
.github/workflows/reuseable_test.yaml
.gitpod.Dockerfile
build-scripts/ubuntu-2004/build-3rd-parties.sh
setup.py

Signed-off-by: Philipp Schlarb <p.schlarb@esatus.com>

GHA deprecation fixes

---

README.md

As someone first coming to this repo I wasn't familiar with which `fabric` this referred to. Hopefully this clarifies it.
Signed-off-by: Matt Mankins <mankins@gmail.com>

docs: clarify fabric source

---

.github/workflows/tag.yaml

- Following fix made here; https://github.com/sovrin-foundation/sovrin/pull/315

fixed correct checkout version & tags fetch

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/README.md
.github/workflows/reuseable_test.yaml
README.md
build-scripts/ubuntu-2004/build-3rd-parties.sh
dev-setup/ubuntu/ubuntu-2004/SetupVMTest.txt
docs/source/ci-cd.md
setup.py

- Inform people of the change to the branch structure.

Add announcement section to README.md

---

MAINTAINERS.md

Signed-off-by: Stephen Curran <swcurran@gmail.com>

indy-plenum Maintainers as of today

---

docs/source/conf.py

Signed-off-by: Stephen Curran <swcurran@gmail.com>

Fix typo in RTD config that prevents build

---

docs/source/conf.py

- Fix typo in RTD config that prevents build
- Doh...another RTD problem missed
Sorry!!! When I did the last one, I said "If I had done a local build that wouldn't have been missed", and then I didn't do a local build.  This time I did...should be the last one.

Doh...another RTD problem missed
