hyperledger/indy-plenum

plenum/config.py

This fixed 6 tests from sovrin_client.test.agent.test_accept_invitation module which had failed on Windows 10 previously.

Increased ExpectedConnectTime setting on Win32 platform.

---

runner.py

According to https://docs.python.org/3.5/library/os.html os.EX_OK and os.EX_SOFTWARE are available  on Unix only

made exit codes portable for Windows platforms

---

plenum/config.py

This is regarding recently introduced reset_client script. As part of this change, we are disabling update of genesis pool txn files whenever any pool changes happens (as per discussion with Lovesh regarding SOV-667)

disabled update genesis pool txn file feature

---

plenum/cli/cli.py

Testing on sovrin-client held with
1 failed, 161 passed, 22 skipped, 3 pytest-warnings
This pull request does not increase any failures/warnings but also does not resolve any within sovrin-client.

Updated copyright

---

plenum/common/zstack.py
plenum/config.py
plenum/test/zstack_tests/test_quotas.py

There was a TODO
```
```
This pull request brings changes that fix it

Fix 'infinit' looping on receiving messages when their amount is very high

---

plenum/common/util.py
plenum/server/node.py
plenum/server/pool_manager.py
plenum/test/helper.py
plenum/test/view_change/test_view_changes_if_backup_primary_disconnected.py
plenum/test/view_change/test_view_changes_if_master_primary_disconnected.py

If primary node went offline pool should start view change

Do view change if a primary is disconnected

---

plenum/common/test_network_setup.py

Bug Fixed: Unable to create pool transaction file on the client machine without passing it a node number

[Closes SOV-981] 

---

plenum/test/instances/test_instance_cannot_become_active_with_less_than_four_servers.py

I made a number of runs in different conditions and it didn't failed, so unskipping it

Unskip testProtocolInstanceCannotBecomeActiveWithLessThanFourServers since it works well

---

plenum/server/pool_manager.py
plenum/test/pool_transactions/helper.py
plenum/test/pool_transactions/test_nodes_ha_change_back.py
plenum/test/pool_transactions/test_nodes_with_pool_txns.py

Case (https://evernym.atlassian.net/browse/SOV-908):
The Node HA is updated with some HA (let's name it 'correct' HA). 
Then the Steward makes a mistake and sends the NODE txn with other HA 
('wrong' HA). The Steward replaces back 'wrong' HA by 'correct' HA sending
yet another one NODE txn.

fix change back HA, SOV-908

---

plenum/common/test_network_setup.py

The changes:
- clean and validate each of IP addresses for parameter --ips
- check --nodes greater than zero
- check --envName can be only 'test' or 'live'

improve the check of the arguments in "generate_sovrin_pool_transactions"

---

plenum/common/script_helper.py
plenum/server/pool_manager.py
plenum/test/helper.py
plenum/test/pool_transactions/conftest.py
plenum/test/pool_transactions/helper.py
plenum/test/pool_transactions/test_nodes_with_pool_txns.py

Check client input for the NODE txn
- the Node txn must contain (NODE_IP, CLIENT_IP, NODE_PORT, CLIENT_PORT, SERVICES)
- fields NODE_IP, CLIENT_IP are IP addresses
- fields NODE_PORT, CLIENT_PORT are integers (0, 65535]
https://evernym.atlassian.net/browse/SOV-1046
https://evernym.atlassian.net/browse/SOV-1064
https://evernym.atlassian.net/browse/SOV-1062

Check client input for the NODE txn

---

plenum/test/input_validation/test_common_checks.py
plenum/test/input_validation/test_handle_one_node_message.py
plenum/test/instances/test_multiple_instance_change_msgs.py
plenum/test/script/test_change_non_primary_node_ha.py
plenum/test/script/test_change_primary_node_ha.py
plenum/test/test_node_connection.py
plenum/test/test_node_request.py
plenum/test/view_change/test_queueing_req_from_future_view.py

- Provided all the disabled tests with the ticket references.
- Enabled the tests testChangeNodeHaForPrimary and testChangeNodeHaForNonPrimary on non-Windows platforms.
- Commented out parametrizers at the disabled tests in plenum.test.input_validation.test_common_checks module.

INDY-73: Updated tests enablement statuses

---

plenum/common/util.py

Current usage of random.choice() is not secure so replaced that with
libsodium provided randombytes_uniform() which is secure and also
available on all platforms where libsodium is available

Use secure random number generator for randomString()

---

plenum/common/util.py
plenum/test/common/test_random_string.py

The current algorithm requires calling the libsodium random function 'size' times where size is the expected length of random string
Changed this so that this will require at the most '(size/64)' number of calls.
Also we do not need the chars list now we always use only alphabets and digits available in hex this makes it very easy and still gives us what we need.
Every instance of usage of this function has been checked and nowhere the 'chars' parameter is used

Make random string generation efficient

---

plenum/server/primary_elector.py
plenum/test/primary_election/test_primary_election_case6.py
plenum/test/test_node.py

if `f` nodes do not send Primary and the node is the last one to send Primary, then it was not able to decide the primary, since a node was doing "primary setting" only on receiving a Primary message, changed that to try "setting primary" after sending Primary too

Election bug fix

---

plenum/cli/cli.py

This line causes the CLI tests to fail because it it is closing and reiniting the stdout file descriptor, which is killing pytest's ability to capture output.
Commenting this line resolves the test failures.
INDY-315

Commented out raet logging

---

plenum/common/messages/message_base.py
plenum/test/input_validation/test_message_serialization.py

Older versions of ujson use dir method of classes for getting fields.
Our message classes contain special service fields like 'typename' and 'schema', which should be excluded from serialized message

Fix serialization of messages when ujson < 1.35 is used

---

plenum/common/messages/node_messages.py
plenum/server/message_req_processor.py
plenum/test/common/test_parse_ledger.py
plenum/test/input_validation/test_message_serialization.py
setup.py

Fixing blocking issue INDY-406:
ujson serializes composite messages (introduced with MsgReq/Rep feature) differently depending on the version. 
- fixed version of ujson to 1.33 (the same as canonical deb in Ubuntu 16)
- expect submessages to be serialized as a dict.

fix ujson version to have the same serialization of composite messages

---

plenum/test/checkpoints/test_message_outside_watermark1.py

- do not do any view changes since we're dealing with non-master instance and may have not order all requests if view is changed

INDY-462: fix testPrimaryRecvs3PhaseMessageOutsideWatermarks test

---

plenum/test/checkpoints/test_message_outside_watermark1.py

- do not do any view changes since we're dealing with non-master instance and may have not order all requests if view is changed
- delay for all nodes (both primary and non-primary), since this is delay for receiving, not sending.

fix testPrimaryRecvs3PhaseMessageOutsideWatermarks

---

build-scripts/ubuntu-1604/build-3rd-parties.sh

The package already exists in the canonical archive

Do not build the ujson deb package

---

plenum/test/checkpoints/test_message_outside_watermark1.py

The delay has to be increased because of the performance fix in
the 'logcapture' function (decreased number of re.search). The tests
became faster so delay=3 was not enough.

Fix 'watermark' test

---

common/serializers/json_serializer.py

JsonSerializer uses either json or ujson backends.
It makes configuration but it uses default settings anyway what leads to serialization problems.
This pr fixes it.

Fix serialization in JsonSerializer

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

- building of python-indy-crypto deb is moved to indy-crypto repo;
- increment indy-crypto version
- indy-crypto is renamed (python3 prefix is removed)

use latest indy-crypto

---

plenum/common/batched.py
plenum/common/ledger_manager.py
plenum/server/node.py
plenum/test/cli/test_long_msg_err.py
plenum/test/client/test_client.py
plenum/test/common/test_splitting_large_messages.py
plenum/test/node_catchup/test_large_catchup.py
plenum/test/replica/test_buffers_cleaning.py
plenum/test/testing_utils.py

Problem is caused by message size limitation - catchup response can be to large.
To solve this this pr introduces mechanism for splitting messages on smaller parts

[INDY-907] Fix problem with catchup of large ledgers

---

Jenkinsfile
Jenkinsfile.cd
build-scripts/ubuntu-1604/build-3rd-parties-docker.sh
build-scripts/ubuntu-1604/build-indy-plenum-docker.sh

- Work around missing "docker volume rm --force" option in older API (< 1.25). So it also works with docker 1.12 provided with CentOS 7 (should not hurt).
- Quote shell variables to support space in paths (always good).
- Support parallel docker builds by adding suffix to volumes in case of multi-branch pipeline (should not change anything for single-branch).
REM: See other PR's for similar improvements in other indy repos (i.e.: for [indy-node](https://github.com/hyperledger/indy-node/pull/381)).

INDY-580: Improve packaging before supporting CentOS

---

plenum/client/client.py
plenum/common/util.py
plenum/test/bls/helper.py
plenum/test/bls/test_no_state_proof.py
plenum/test/bls/test_state_proof.py
plenum/test/client/test_client_resends_not_confirmed_request.py
plenum/test/client/test_client_sends_get_request_to_one_node.py
plenum/test/test_node.py
plenum/test/testable.py

Before this PR client was able to send request to one node if there is no sufficient connections.
This PR makes it send to one node always.

[INDY-927] Make client send read only reqeusts to one node

---

plenum/server/node.py
plenum/server/propagator.py
plenum/test/monitoring/test_no_check_if_no_new_requests.py

Do not do performance check if there is no new requests since last check. 
It prevents infinit sending of InstanceChange messages if other nodes do not reply to it.

Fix infinit InstanceChange when no new requests

---

ledger/compact_merkle_tree.py
ledger/ledger.py
ledger/merkle_tree.py
ledger/test/conftest.py
ledger/test/test_ledger.py

- fixed recovering merkle tree after restart from txn log, if recovering from hash store failed because of consistency verification error (it can be since add to ledger is not atomic operation).

INDY-893: fix recovering tree from txn log

---

plenum/common/messages/client_request.py
plenum/server/node.py
plenum/test/input_validation/test_client_get_txn_op.py
plenum/test/pool_transactions/test_get_txn_request.py
stp_core/common/log.py

Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>

add-ledgerId field in validator

---

plenum/common/ledger_manager.py
plenum/common/txn_util.py
plenum/config.py
plenum/test/helper.py
plenum/test/waits.py
scripts/add_json_txns_to_ledger.py
scripts/generate_txns.py

[INDY-1029] Change timeout for getting cathup replies

---

plenum/common/test_network_setup.py

Added appending of CLIENT_CONNECTIONS_LIMIT to env file by writeNodeParamsFile() function.

INDY-1087: add appending of CLIENT_CONNECTIONS_LIMIT to env file

---

plenum/server/view_change/view_changer.py

[INDY-1116] fix IstanceChanges queue cleanup while view change completed

---

docs/main.md
plenum/common/batched.py
plenum/server/node.py
plenum/server/pool_manager.py

Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>

documentation, change log message and method names

---

plenum/server/pool_req_handler.py
plenum/test/pool_transactions/test_node_adding.py

add dynamic validation of alias and test

[INDY-1148] It's possible to create several nodes with the same alias

---

stp_core/common/log.py

[INDY-1102] Fix Logger setting

---

plenum/test/delayers.py
plenum/test/node_request/test_timestamp/test_timestamp_post_view_change.py
plenum/test/stasher.py
plenum/test/test_stasher.py

Changes:
- implemented `delay_rules` context manager to simplify delay rules management in tests
- fixed some internals of Stasher and documented possible corner cases
- added default (large) timeouts to most of delay rule functions
- refactored one of existing tests to show example of intended usage of new `delay_rules` context manager
Overall this new context manager should help write less error prone and more deterministic integration tests.

Context manager for delay rules in stasher

---

plenum/server/node.py
plenum/test/restart/test_restart_nodes.py

Send ledger status to new nodes in all cases; test for node restart

---

plenum/server/replica.py

Fix none finalised reqs in case of not participating

---

plenum/server/domain_req_handler.py
plenum/test/bls/test_make_proof.py
state/pruning_state.py

[INDY-1137] Making proof possible for given root hash

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
ci/ubuntu.dockerfile

Remove test repo from CI docker.

---

plenum/common/ledger_manager.py
plenum/server/node.py
plenum/test/primary_selection/test_add_node_with_f_changed.py
stp_core/loop/eventually.py

[INDY-1206] select_primaries now called after poolLedger catchup or if we are ordering node txn

---

plenum/common/batched.py
plenum/server/has_action_queue.py
plenum/server/node.py
plenum/server/notifier_plugin_manager.py
plenum/server/propagator.py
plenum/server/replica.py
stp_zmq/kit_zstack.py
stp_zmq/zstack.py

Downgraded severity of some messages from debug to trace

---

scripts/process_logs/README.md
scripts/process_logs/example_network.yml
scripts/process_logs/example_process.yml
scripts/process_logs/example_track_req.yml
scripts/process_logs/example_view_change.yml
scripts/process_logs/process_logs
scripts/process_logs/process_logs.yml

- added option to split output logs by replica
- added simple taggers for request received/ordered events

Log processor improvements

---

stp_core/config.py
stp_zmq/test/conftest.py
stp_zmq/test/test_quotas.py
stp_zmq/test/test_zstack.py

[INDY-1238] Limit zmq queue with 10000 msgs

---

plenum/common/messages/fields.py
plenum/test/helper.py
plenum/test/input_validation/fields_validation/test_iterable_field.py

Signed-off-by: Lovesh Harchandani <lovesh.bond@gmail.com>

add min, max length support to iterables

---

plenum/server/monitor.py
plenum/test/monitoring/test_request_time_tracker.py
plenum/test/monitoring/test_warn_unordered_log_msg.py

Fixed memory leak in monitoring

---

plenum/common/ledger_manager.py
plenum/server/replica.py

INDY-1259: fix typo.

---

plenum/config.py
plenum/test/pool_transactions/helper.py
plenum/test/pool_transactions/test_nodes_data_changed.py
plenum/test/script/test_change_non_primary_node_ha.py
plenum/test/test_log_rotation.py
stp_core/config.py

Fixed log rotation config

---

scripts/process_logs/README.md
scripts/process_logs/process_logs

Log processor: improved request tracking

---

plenum/test/instances/test_instance_cannot_become_active_with_less_than_four_servers.py
plenum/test/monitoring/test_post_monitoring_stats.py

[Fixed failed tests] Decrease reconnect timeout and ensure the same data

---

plenum/config.py
plenum/server/notifier_plugin_manager.py
plenum/test/plugin/test_notifier_plugin_manager.py

Changed math of node request and cluster throughtput spikes detection.
The main changes:
* Now smothing constant (alpha) is really constant as declares exponential
moving average (EMA), alpha = 2 / (N + 1), where N is a minimal count of
passed periods needed for comparison of expected value and real value, a.g.
learning period. For now N = 15, so alpha = 0.125.
* Rised min activity from 2 to 10, a.g. we start to compare expected and real
values if we handle more than 10 request per time period, that now is set
to 60 secs (10 requests per minute).
* Rised borders coefficient to extend the lower and higher borders when observed
value is treated as normal relative to expected value, previous border coefficient = 3:
- lower border:  expected_val / 3
- higher border: expected_val * 3
new …

INDY-1251: change math of spikes detection.

---

setup.py

A new version of the base58 1.0.0 was released. The format of the response of the b58encode() was changed from string to bytes.
Changes:
-fix base58 0.2.5 version

INDY-1287: fix base58 version

---

plenum/test/plugin/test_notifier_plugin_manager.py

INDY-1251: fix data in notifier plugin tests and unskip them.

---

plenum/config.py
plenum/test/test_log_rotation.py
stp_core/common/log.py
stp_core/common/logging/CompressingFileHandler.py
stp_core/common/logging/TimeAndSizeRotatingFileHandler.py
stp_core/config.py

- Added xz compression option
- Moved compression to separate process
- Removed rotation date from log filenames
- Removed time rotation logic

INDY-1273/1275: Log rotation improvements

---

plenum/server/validator_info_tool.py

[RUN_CMD] Catch stderr if external cmd flush error into stderr (jouralctl inside docker containers for example)

---

plenum/common/txn_util.py
plenum/test/transactions/test_new_txn_format.py

[txnId_Fix] Add txn_id while metadata appending (if exist)

---

plenum/recorder/replayer.py
plenum/test/recorder/test_replayer.py

Non-impacting output to console to help the user see progress
Fixed a bug for replays that don't have an end time on the last segment
Prod node on every loop
Signed-off-by: Devin Fisher <devin.fisher@evernym.com>

Add progress info to output of replay

---

plenum/server/domain_req_handler.py
plenum/server/ledger_req_handler.py
plenum/test/test_node.py

Add missed txnId to txn in ledger

---

plenum/server/replica.py
plenum/test/checkpoints/test_checkpoints_removal_after_catchup_during_view_change.py

- Fixed a bug in the logic of stashed checkpoints removal which appeared after a catch-up performed during view change.
- Added tests which verify stashed checkpoints removal on master and backup replicas after a catch-up performed during view change.

INDY-1427: Fix bug in stashed checkpoints removal

---

common/serializers/signing_serializer.py
common/test/test_signing_serializer.py
plenum/common/txn_util.py
plenum/server/message_handlers.py
plenum/server/node.py

- use correct Request class when processing requested PROPAGATE (since request class is overridden in indy-node)
- use correct Request class in 
- the tests are in `reqTotxn` (since request class is overridden in indy-node)
- fixed a small issue in SigningSerializer
- added tests for SigningSerializer (there is an issue there: INDY-1469)
- the tests for propagation of ATTRIB are in https://github.com/hyperledger/indy-node/pull/816

INDY-1464: fix Propagate request for ATTRIB txn

---

plenum/test/view_change_with_delays/test_view_change_with_different_prepare_certificate.py

Check that a node without pre-prepare but with quorum of prepares wouldn't use this transaction as a last in prepare certificate

INDY-1461: add the test for different prepare certificates in view change

---

plenum/config.py
plenum/server/monitor.py
plenum/test/monitoring/test_avg_latency.py
plenum/test/monitoring/test_instance_change_with_req_Lambda.py
plenum/test/monitoring/test_latency_measurement_class.py
plenum/test/monitoring/test_monitoring_params_with_zfn.py
plenum/test/monitoring/test_request_measurement_class.py
plenum/test/monitoring/test_throughput_measurement_class.py

[INDY-1468] move avgLatency computing to EMA algorithm

---

plenum/recorder/replayable_node.py

The replayable node's version of consume_req_queue_for_pre_prepare must
produce the same return signature as defined in the Replica class
Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>

Must return a 4-tuple from consume_req_queue_for_pre_prepare

---

plenum/common/batched.py
plenum/common/metrics_collector.py
plenum/common/metrics_stats.py
plenum/common/prepare_batch.py
plenum/common/stacks.py
plenum/common/types.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/test_metrics_collector.py
plenum/test/test_metrics_config.py
plenum/test/test_metrics_stats.py
stp_zmq/zstack.py

INDY-1475: Preparation for statistics processing script

---

stp_zmq/remote.py
stp_zmq/zstack.py

Now we are able to specify a NIC for communication explicitly
for full multi-NIC support.

INDY-1531: add bind-before-connect to control outgoing routing.

---

plenum/server/replica.py
plenum/test/checkpoints/test_checkpoints_removal_in_view_change.py

Fix that a checkpoints finalize cleans necessary data from requests and 3pc queues  in view change before catchup.
Changes:
- add bugfix for view_no in checkpoint cleaning in view change. Choose view_no from last_ordered_3pc
- update test test_checkpoints_removal_in_view_change.py

INDY-1545: stop processing checkpoints in view change

---

plenum/common/value_accumulator.py
plenum/test/metrics/test_value_accumulator.py

INDY-1543: Fix crash in stddev, add average bounds

---

plenum/server/pool_req_handler.py
plenum/test/req_handler/test_pool_req_handler_static_validation.py

Added to the pool_req_handler static validation of message with not None key proof and without bls key.

INDY-1389: added check to case with bls key proof without key

---

plenum/bls/bls_key_register_pool_manager.py
plenum/server/pool_req_handler.py
plenum/test/bls/test_bls_not_depend_on_node_reg.py
state/pruning_state.py
state/test/test_pruning_state.py

INDY-1583: Fix bls signature checking 

---

plenum/server/node.py
plenum/test/checkpoints/helper.py
plenum/test/checkpoints/test_stable_checkpoint.py
plenum/test/checkpoints/test_view_change_after_checkpoint.py

- Modified the test verifying requests removal from Propagator.requests collection on checkpoint stabilization: now removal of rejected requests is also verified.
- Corrected a related test helper-function and tests using it.
- Fixed a bug with lack of removing rejected requests from Propagator.requests collection.

INDY-1700: Removing rejected reqs from Propagator

---

plenum/common/ledger_manager.py
plenum/test/node_catchup/test_node_catchup_with_connection_problem.py

- Corrected the test of cancellation of scheduled re-asking for ledger statuses and maximal consistency proofs on reception of sufficient count of messages.
- Fixed cancellation of scheduled re-asking for ledger statuses and maximal consistency proofs which was not operable previously.

INDY-1740: Fixed a bug in re-asking cancellation

---

plenum/server/pool_manager.py
plenum/test/pool_transactions/test_suspend_node.py

INDY-1719: Fix for node demotion

---

plenum/test/node_catchup/test_catchup_not_triggered_if_another_in_progress.py
plenum/test/node_catchup/test_catchup_start.py
plenum/test/node_catchup/test_node_catchup_after_checkpoints.py
plenum/test/test_node.py

- Added unit tests verifying ability to start catchup in different node modes.
- Reduced execution time of the integration test verifying that a catchup cannot be started if another catchup is in progress.
- Removed a not needed execution time limit override from an existing test.

INDY-1739: Unit tests for ability to start catchup

---

plenum/server/message_handlers.py
plenum/server/node.py
plenum/test/node_request/test_request_schema_validation.py

- Eliminated repeated validations of a write request against the schema on handling of one Propagate message and on handling one MessageRep with Propagate.
- Added tests verifying the count of request schema validation times on handling a write request from a client and on handling Propagate.
- Corrected limitation of the length of a log message in `Node.validateClientMsg` method.

INDY-1753: Eliminated request schema re-validation

---

stp_core/loop/looper.py

Warn if looper iteration is too long

---

plenum/server/replica.py
plenum/test/checkpoints/test_backup_replica_resumes_ordering_on_lag_in_checkpoints.py
plenum/test/checkpoints/test_stashed_messages_processed_on_backup_replica_ordering_resumption.py
plenum/test/checkpoints/test_watermarks_on_delayed_backup.py
plenum/test/conftest.py
plenum/test/primary_selection/test_primary_selection.py

- Added a test verifying resumption of ordering 3PC-batches on a backup replica on detection of a lag in checkpoints.
- Added a variant of the test verifying resumption of ordering in case the lag is detected after some batch in the next checkpoint has already been committed but cannot be ordered out of turn.
- Added a variant of the test verifying resumption of ordering in case the lag is detected after some 3PC-messages related to the next checkpoint have already been stashed as laying outside of the watermarks.
- Implemented resumption of ordering 3PC-batches on a backup replica on detection of a lag in checkpoints.
- Corrected one existing test according to the made changes.
- Removed an unused fixture.

INDY-1795: Resume ordering on backup replica

---

plenum/server/monitor.py
plenum/test/replica/test_replica_removing_with_backup_degraded.py

Changes:
- remove checking is_instance_avg_req_latency_too_high() from areBackupsDegraded()
- added test_replica_not_degraded_with_too_high_latency

INDY-1815: areBackupsDegraded() are not use latency anymore

---

plenum/common/metrics_collector.py
plenum/server/node.py

Add GC-related metrics

---

plenum/common/util.py
stp_zmq/zstack.py

INDY-209: Additional formatting

---

plenum/server/node.py
plenum/server/replica.py
plenum/test/batching_3pc/catch-up/test_clearing_requests_after_catchup.py
plenum/test/malicious_behaviors_node.py
plenum/test/primary_selection/test_primary_selector.py

INDY-1881: Catchup clearing

---

plenum/server/node.py
plenum/test/conftest.py
plenum/test/node/test_api.py
plenum/test/view_change/test_client_req_during_view_change.py
plenum/test/view_change/test_client_req_during_view_change_integration.py

Changes:
- move View Change check in unpackClientMsg and add check for request type
- add tests

INDY-1896: Allow "read" and "action" requests processing

---

plenum/common/stack_manager.py
plenum/server/pool_manager.py
plenum/test/pool_transactions/conftest.py
plenum/test/pool_transactions/test_add_node_with_invalid_key_proof.py
plenum/test/pool_transactions/test_nodes_data_changed.py
plenum/test/pool_transactions/test_on_pool_membership_changes.py
plenum/test/pool_transactions/test_txn_pool_manager.py

- remove getNodeData fron PoolManager
- remove getAllTxn from nodeServicesChanged
- remove getAllTxn from onPoolMembershipChange
- getNodeName - change to using _ordered_node_ids

INDY-1879: faster way for pool transactions ordering

---

plenum/config.py
plenum/test/conftest.py
stp_zmq/zstack.py

ToleratePrimaryDisconnection increased up to 60 seconds.
The bind re-try time increased up to 10 seconds.

INDY-1836: increase ToleratePrimaryDisconnection and bind re-try time.

---

plenum/server/monitor.py
plenum/server/node.py
plenum/test/monitoring/test_request_time_tracker.py
plenum/test/req_drop/test_req_drop.py

INDY-1836: clear monitor data related to dropped request.

---

plenum/config.py
plenum/server/replicas.py
plenum/test/conftest.py
stp_zmq/zstack.py

INDY-1836: increase ToleratePrimaryDisconnection and bind re-try time.
ToleratePrimaryDisconnection increased up to 60 seconds.
The bind re-try time increased up to 10 seconds.
INDY-1926: add check for None of replica's primary name during logging.

Cherry-pick INDY-1836/INDY-1926

---

plenum/server/node.py
plenum/server/propagator.py
plenum/server/replica.py
plenum/server/replicas.py
plenum/test/req_drop/test_req_drop_when_backup_replica_does_not_order.py
plenum/test/requests/test_req_state.py

Also added a new counter unordered_by_replicas_num for req_state
to check how many replicas have not yet ordered particular
request.

INDY-1836: add test of req drop when replica does not order.

---

design/catchup-and-audit-proposal.md

INDY-1924: Catchup and audit design proposal

---

plenum/server/node.py
plenum/server/replica.py
plenum/server/replica_validator.py
plenum/test/batching_3pc/catch-up/test_clearing_requests_after_catchup.py
plenum/test/batching_3pc/catch-up/test_freeing_forwarded_not_preprepared_request.py
plenum/test/batching_3pc/catch-up/test_freeing_forwarded_preprepared_request.py
plenum/test/batching_3pc/helper.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_checkpoints.py
plenum/test/replica/helper.py

Changes:
- allLedgersCaughtUp() refactoring
- change order of stashing in replica_stasher. Now messages append to view change or catchup stash queue. And if it does not happen, check for out of watermarks.

INDY-1876: Change order of stashing

---

plenum/server/replica.py
plenum/server/replica_stasher.py
plenum/test/req_drop/test_req_drop_on_preprepare_phase_non_primary.py

Add logging for a while. Return after solving the task  INDY-1949.

 INDY-1949: Add more logging

---

plenum/server/replica.py
plenum/test/checkpoints/helper.py
plenum/test/checkpoints/test_checkpoint_stabilization_after_catchup.py
plenum/test/helper.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_checkpoints.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_only_checkpoints.py
plenum/test/node_catchup_with_3pc/test_stashing_checkpoints_after_view_change.py

INDY-1955: fixing infinite catch-up

---

plenum/common/ledger_uncommitted_tracker.py
plenum/common/tracker.py
plenum/test/tracker/test_ledger_uncommitted_tracker.py
plenum/test/tracker/test_tracker.py

Signed-off-by: Cam Parra <caeparra@gmail.com>

[WIP]INDY-1874 General Tracker 

---

plenum/common/ledger_manager.py
plenum/server/replica.py
plenum/test/node_catchup/catchup_req/conftest.py
plenum/test/node_catchup/catchup_req/test_catchup_with_disconnected_node.py
plenum/test/node_catchup/catchup_req/test_catchup_with_one_slow_node.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_checkpoints.py
plenum/test/node_request/test_node_got_only_preprepare.py

INDY-1955: don't send CatchupReq to disconnected and unresponsive nodes

---

plenum/config.py
plenum/server/monitor.py
plenum/test/monitoring/test_backup_throughput_measurement.py

INDY-1933: Fix for backup throughput measuring

---

plenum/common/ledger_uncommitted_tracker.py
plenum/test/stasher.py
plenum/test/tracker/test_ledger_uncommitted_tracker.py

[INDY-1874] add set_last_committed and delay_without_unstash for tests

---

build-scripts/ubuntu-1604/build-3rd-parties.sh
plenum/common/messages/fields.py
plenum/common/version.py
plenum/test/common/version/test_version.py
plenum/test/input_validation/fields_validation/test_version_field.py
setup.py

Changes:
- classes to abstract version API
- update for version field validation
- new dependency `packaging==19.0` to support PEP440 (PyPI versioning)

[INDY-1992] Adds base classes to support versioning routine

---

plenum/common/ledger_manager.py
plenum/server/catchup/catchup_rep_service.py
plenum/server/catchup/cons_proof_service.py
plenum/server/catchup/ledger_leecher_service.py
plenum/server/catchup/node_leecher_service.py
plenum/server/catchup/utils.py
plenum/server/node.py
plenum/server/validator_info_tool.py
plenum/test/batching_3pc/helper.py
plenum/test/conftest.py
plenum/test/node_catchup/helper.py
plenum/test/node_catchup/test_get_last_txn_3PC_key.py
plenum/test/node_catchup/test_new_node_catchup.py
plenum/test/node_catchup/test_node_catchup_after_restart_after_txns.py
plenum/test/node_catchup/test_node_ledger_manager.py
plenum/test/node_catchup/test_process_catchup_replies.py
plenum/test/node_catchup/test_same_ledger_initial_catchup.py
plenum/test/plugin/demo_plugin/conftest.py
plenum/test/test_ledger_manager.py

INDY-1945: Implement NodeLeecherService

---

plenum/server/batch_handlers/audit_batch_handler.py
plenum/server/batch_handlers/three_pc_batch.py
plenum/server/node.py
plenum/server/replica.py
plenum/test/view_change/test_no_propagate_request_on_different_last_ordered_before_vc.py

INDY-2032: extend logging

---

plenum/config.py
plenum/server/replica_validator.py
plenum/test/replica/test_max_3pc_batches_in_flight.py
plenum/test/replica/test_replica_3pc_validation.py

INDY-1863: Allow limiting maximum number of 3PC batches in flight

---

plenum/server/view_change/view_changer.py
plenum/test/freshness/test_freshness_in_catchup.py
plenum/test/freshness/test_freshness_view_change.py

Do not check freshness in a catchup.

---

state/util/utils.py
storage/kv_store_file.py

- Prefer hashlib.sha3_256 when it's available (in python 3.6+) - the sha3 module is not compatible
- Fix a type checking error that occurs in python 3.6+
This is an update of PR #714

Fixes for Python 3.6 support

---

plenum/common/event_bus.py
plenum/common/router.py
plenum/common/stashing_router.py

INDY-2169: Allow to unsubscribe from event buses

---

plenum/common/timer.py
plenum/server/catchup/cons_proof_service.py
plenum/test/node_catchup/test_node_catchup_with_connection_problem.py
plenum/test/node_catchup_with_3pc/test_stashing_3pc_while_catchup_only_checkpoints.py

INDY-2215: add re-ask LedgerStatuses for the init catchup

---

plenum/common/exceptions.py
plenum/common/util.py
plenum/test/blacklist/test_blacklist_client.py
plenum/test/client/test_client.py
plenum/test/util/test_common_util.py

In order not to break how certain exceptions work now,
the scope of new formating is now contained to only some
exception types.

[INDY-2103] Minor changes to how exception formating is done

---

plenum/common/messages/internal_messages.py
plenum/server/consensus/ordering_service.py
plenum/server/consensus/view_change_service.py
plenum/test/consensus/order_service/sim_helper.py
plenum/test/consensus/order_service/test_sim_order_during_view_change.py
plenum/test/consensus/view_change/helper.py
plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/helper.py
plenum/test/simulation/sim_network.py
plenum/test/simulation/test_sim_network.py

INDY-2223: Improve simulation tests

---

plenum/server/consensus/view_change_service.py
plenum/test/consensus/view_change/test_view_change_service.py
plenum/test/test_node.py
plenum/test/view_change/test_new_primary_lagging_behind.py

[INDY-2230] do not send NewView msg if primary is behind

---

plenum/server/consensus/ordering_service.py
plenum/server/message_handlers.py
plenum/server/node.py
plenum/server/propagator.py
plenum/server/replicas.py
plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/node_request/message_request/test_preprepare_request.py
plenum/test/node_request/test_propagate/test_node_lacks_finalised_requests.py
plenum/test/node_request/test_propagate/test_node_request_only_needed_propagates.py
plenum/test/node_request/test_propagate/test_node_request_propagates_with_delay.py
plenum/test/replica/test_replica_received_preprepare_with_unknown_request.py

- Primary still uses finalized requests to be included into PrePrepare
- Non-primaries process requests from PrePrepare if they are aware of it (either received a request or at least one Propagate). This is a step towards Aardvark protocol. Also we have digital signatures, so are sure requests came from the clients. In order to check that Primary doesn't skip any requests, other means and checks are needed in any case (regardless if this is RBFT or Aardvark), and this has nothing to do with finalized requests.
- Return even non-finalized requests when processing Propagate MessageReq

INDY-2244: optimize finalized requests logic

---

stp_core/config.py
stp_zmq/zstack.py

A try to deal with reconnections by always using the latest connection with the same ID (all our Nodes use the same ID equal to the pubkey).

INDY-2261: add ROUTER_HANDOVER option

---

plenum/test/restart/test_reconnect.py
stp_zmq/test/test_stashing_unknown_remote_msgs.py
stp_zmq/zstack.py

Signed-off-by: Nemanja Patrnogic <3052405+donqui@users.noreply.github.com>

[INDY-2289]: Additional tests

---

stp_zmq/test/test_no_size_limit_for_outbound_msgs.py
stp_zmq/test/test_zstack.py
stp_zmq/zstack.py

Signed-off-by: Nemanja Patrnogic <3052405+donqui@users.noreply.github.com>

[INDY_2306]: Remove size limit for outbound msgs

---

plenum/server/consensus/view_change_storages.py
plenum/test/consensus/test_consensus_shared_data.py
plenum/test/demotion_promotion/test_demote_from_10_to_4_nodes.py
plenum/test/demotion_promotion/test_demote_promote_7_nodes.py

[INDY-2326] add another demotion/promotion tests and fix

---

scripts/test_zmq/README.md
scripts/test_zmq/check_zmq.sh
scripts/test_zmq/common/Dockerfile
scripts/test_zmq/setup.py
scripts/test_zmq/test_zmq/__init__.py
scripts/test_zmq/test_zmq/__version__.py
scripts/test_zmq/test_zmq/authenticator.py
scripts/test_zmq/test_zmq/client.py
scripts/test_zmq/test_zmq/crypto/encoding.py
scripts/test_zmq/test_zmq/crypto/nacl_wrappers.py
scripts/test_zmq/test_zmq/crypto/signer.py
scripts/test_zmq/test_zmq/crypto/util.py
scripts/test_zmq/test_zmq/server.py
scripts/test_zmq/test_zmq/util.py
scripts/test_zmq/test_zmq/zstack.py

[INDY-2330] Tool for checking zmq connection

---

plenum/common/constants.py
plenum/common/txn_util.py
plenum/test/transactions/test_req_to_txn.py
plenum/test/transactions/test_txn_init_utils.py

INDY-2338: support generic way for request payload version

---

plenum/server/consensus/ordering_service.py
plenum/server/node.py
plenum/test/batching_3pc/test_basic_batching.py
plenum/test/client/helper.py
plenum/test/client/test_client_send_wrong_ledger_status.py
plenum/test/client/test_protocol_version.py
plenum/test/client/test_send_from_wrong_socket.py
stp_zmq/zstack.py

[FIX] fix client-related behaviour

---

plenum/server/client_error_codes.py
plenum/server/request_handlers/txn_author_agreement_handler.py
plenum/server/request_managers/write_request_manager.py
plenum/test/txn_author_agreement/acceptance/test_taa_acceptance_validation.py
plenum/test/txn_author_agreement/test_txn_author_agreement.py

'datetime.utcfromtimestamp'  throws ValueError exception if a timestamp in milliseconds.

Add validations for TAA_ACCEPTANCE_TIME and timestamps in the TAA txn

---

Jenkinsfile.cd
build-scripts/ubuntu-1604/build-3rd-parties.sh
setup.py

Bumped version of python-ursa to 0.1.1. This version includes sources distribution that is required by pipelines.

Fixing CD pipeline

---

.github/workflows/build.yaml
build-scripts/ubuntu-1604/build-3rd-parties.sh
build-scripts/ubuntu-1604/build-indy-plenum.sh
build-scripts/ubuntu-1604/install-os-dependencies.sh
build-scripts/ubuntu-1604/install-os-tools.sh
build-scripts/ubuntu-1604/upgrade-git.sh

Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
Rebased CD changes into a single commit

Github actions CD steps for plenum

---

docs/source/transaction_freeze_ledgers.md

Signed-off-by: anton.denishchenko <anton.denishchenko@dsr-corporation.com>

Add doc for freeze ledger

---

.github/workflows/build.yaml
.github/workflows/build/Dockerfile
build-scripts/ubuntu-1604/build-3rd-parties.sh

- Extended the Dockfile with the CD dependencies. It's not necessary anymore to install dependencies and fpm in build_plenum_release job
- split the build_plenum_release job into two jobs
- (1) build plenum release and upload deb file as an artifact
- (2) build all 3rd party dependencies and cache them. Only trigger a new build if the dependencies change

Split CD release into two parts, added caching, and extended Docker file

---

plenum/test/consensus/view_change/test_sim_view_change.py

Skip problem seeds for view change simulation tests. 

---

plenum/test/conftest.py

Signed-off-by: Devin Smith <devinleighsmith@gmail.com>

check if record.message exists with hasattr or use record.msg

---

ci/ubuntu.dockerfile
plenum/test/consensus/view_change/test_sim_view_change.py
plenum/test/freeze_ledgers/helper.py
setup.py

Signed-off-by: toktar <renata.toktar@evernym.com>

UP-34: bump libindy, use ledgers_freeze from libindy for tests

---

.github/workflows/build.yaml
.github/workflows/build/Dockerfile.ubuntu-20-04
runner.py

Signed-off-by: Devin Smith <devinleighsmith@gmail.com>
bringing visibility to test failures in the 20.04 build of indy-plenum.
see https://github.com/devinleighsmith/indy-plenum/actions/runs/731553669 to view the test failures.

Update runner to be compatible with python 3.8, pytest 6.2.2

---

.github/workflows/lint/Dockerfile
plenum/__init__.py
plenum/server/notifier_plugin_manager.py
plenum/server/validator_info_tool.py
plenum/test/conftest.py
plenum/test/helper.py
plenum/test/plugin/test_notifier_plugin_manager.py
scripts/test_zmq/common/Dockerfile
setup.py

This uses the backported `importlib_metadata` module to scan for installed packages instead of importing pip, which should remove the dependency on pip < 10. As of Python 3.9 it is equivalent to using `importlib.metadata`.

Remove pip imports in favor of importlib_metadata

---

.github/workflows/build.yaml
build-scripts/ubuntu-1604/build-indy-plenum.sh
build-scripts/ubuntu-1604/prepare-package.sh

This PR contains the building and publishing of the Python package of Plenum to PyPI.
A successful test tun of the PR can be found in this [GHA run](https://github.com/udosson/indy-plenum/actions/runs/1037939572). For testing purposes, the indy-plenum package was published to [TestPyPi](https://test.pypi.org/simple/). The indy-plenum package of the test can be installed via `python3 -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple indy-plenum==1.13.0.dev133`.
@ryjones could you create a secret called `PYPI_API_TOKEN` according to[ PyPI docs](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github), please? This is needed to publish the package to PyPI. …

Python packaging and uploading to PyPI

---

.github/workflows/build/Dockerfile.ubuntu-20-04
.github/workflows/lint/Dockerfile.ubuntu-16-04
.github/workflows/lint/Dockerfile.ubuntu-20-04
plenum/__init__.py
plenum/server/notifier_plugin_manager.py
plenum/server/validator_info_tool.py
plenum/test/conftest.py
plenum/test/helper.py
plenum/test/plugin/test_notifier_plugin_manager.py
scripts/test_zmq/common/Dockerfile
setup.py

This PR solves issue #1549. The PR just applies the adjustments made by @andrewwhitehead in this [commit](https://github.com/hyperledger/indy-plenum/pull/1548/commits/4cd59f88cddf9c13f1f73e2b1bf91cd48504d29a) to the `ubuntu-20.04-upgrade` feature branch. Thanks to @andrewwhitehead for his contribution.

Ubuntu 20.04: remove pip imports in favor if importlib_metadata

---

.github/workflows/build.yaml

- For example, support publishing off the `ubuntu-20.04-upgrade` branch.
- Determine the `distribution` based on the version of Ubuntu being used for the build.

Support publishing off a development branch

---

.github/workflows/build.yaml
build-scripts/ubuntu-1604/build-indy-plenum.sh
build-scripts/ubuntu-1604/prepare-package.sh
build-scripts/ubuntu-2004/build-indy-plenum.sh
build-scripts/ubuntu-2004/prepare-package.sh

This PR solves Issue #1555 and integrates the publishing of the Python package of Plenum to PyPI into the existing GHA workflow.
A successful run of the publishing to (Test)PyPI can be found [here](https://github.com/udosson/indy-plenum/actions/runs/1101535181).
The published Python package of Plenum can be found on Test-PyPI [indy-plenum 1.13.0.dev238](https://test.pypi.org/project/indy-plenum/1.13.0.dev238/)

Ubuntu 20.04: Publishing of Python packages to PyPI

---

.github/workflows/build.yaml

This PR fixes two things:
- The cache key of the uploading of the 3rd party dependencies (deb) was different than the one from `build_3rd_party_dependencies` --> now the same
- When re-running all jobs of the pipeline and if the python packages have already been uploaded to PyPi in the previous one this caused an error --> now fixed by `skip existing`. (Solution was provided by @WadeBarnes)

Bug fix: Cache of 3rd party dependencies & uploading of existing packages to PyPI 

---

.github/workflows/build.yaml

A small change that pins the `lint` docker image to the `ubuntu-18-04` label

added label to pull correct lint image

---

.github/actions/publish-deb/publishPackages
.github/actions/publish-deb/upload-spec.json

This small PR changes the structure of the artifacts uploaded to jfrog artifactory. This is because of conflicts that emerge when uploading deb files with the same name but different distributions.
The new structure will be as follows:
- `indy/pool/xenial/[dev, main, rc, stable]`
- `indy/pool/bionic/[dev, main, rc, stable]`
- `indy/pool/focal/[dev, main, rc, stable]`
Thanks to @WadeBarnes for the discussions we had about this.
The current error can be seen at https://github.com/hyperledger/indy-plenum/runs/3325278452?check_suite_focus=true `Publish 3rd Party Dependencies`.
>Note! A manual clean-up of the current artifacts stored in the jfrog artifactory is needed.

fix uploading of deb files with the same name but different distribution

---

.github/actions/publish-deb/publishPackages
.github/actions/publish-deb/upload-spec.json

This PR cherry-picks the commit from #1563 and applies the same structure of uploading the debian packages to the `ubtuntu-20.04-upgrade` feature branch.

Ubtuntu 20.04: fix uploading of deb files with the same name but different distribution

---

.github/workflows/build.yaml

This PR updates the GitHub Action `setup-jfrog-cli` from `v1` to `v2`. The default version of the `jfrog-cli` changes from `v1.51.1` to `v2.3.0`.

updated version of setup-jfrog-cli to v2

---

build-scripts/ubuntu-1604/build-3rd-parties.sh

Bump version of `zipp` from `1.0.0` to `1.2.0` because `zipp==1.0.0` depends on `more-itertools`. To reduce the number of dependencies this PR updates `zipp` to version `1.2.0` that doesn't depend on additional PyPI packages anymore.

bump version of zipp to 1.2.0

---

.github/workflows/build/Dockerfile.ubuntu-2004
build-scripts/ubuntu-2004/build-3rd-parties.sh

This PR retrieves the most recent version of the third-party dependencies and includes the version number into the name of the artifacts published to Artifactory. This is needed because without it the artifacts get published with version `0.0.0` e.g.  `python3-importlib-metadata_0.0.0_amd64.deb` (https://hyperledger.jfrog.io/ui/native/indy/pool/focal/dev/i/importlib-metadata)

added versions of 3rd party packages to Debian artifacts

---

build-scripts/ubuntu-2004/build-3rd-parties.sh
setup.py

This PR pins the version of `importlib-metadata` to `v3.10.01`. From version `4.0.0`  on, the resulting package ends in `python3-importlib-metadata_0.0.0_amd64.deb`.
The issue can be seen at: https://github.com/hyperledger/indy-plenum/runs/4166593170?check_suite_focus=true#step:5:5304 

pinned version of importlib-metadata because of issue with fpm

---

.github/workflows/build/Dockerfile.ubuntu-2004
build-scripts/ubuntu-1604/build-3rd-parties.sh
build-scripts/ubuntu-1604/build-indy-plenum.sh
build-scripts/ubuntu-2004/build-3rd-parties.sh
build-scripts/ubuntu-2004/build-indy-plenum.sh
build-scripts/ubuntu-2004/requirements.txt
dev-setup/ubuntu/ubuntu-2004/SetupVMTest.txt
plenum/test/conftest.py
setup.py
stp_zmq/remote.py
stp_zmq/zstack.py

- Upgrade to the latest version of `pyzmq`, and update warning filters to ignore the new format of the unclosed socket messages.
- Clean up PAIR sockets as best as possible.
- Fix issue with building the deb for `pyzmq`.

Upgrade zmq

---

.github/workflows/PR.yaml
.github/workflows/releasepr.yaml

Added `StatusCheck` job  (Always true, when executed) for the branch protection rules(blocks merging while test are running and if tests fail).
Job needs to be ran at least once to be able to select it in the branch protection rule settings.

Addition of StatusCheck for branch protection

---

Jenkinsfile.cd

- SovrinHelpers v2.2.4 includes an update to fix dependency issues in `pypi-publish.dockerfile` and `pr-automerge.dockerfile` affecting the CD pipeline.

Upgrade to SovrinHelpers v2.2.4

---

Jenkinsfile.cd

- SovrinHelpers v2.2.5 includes an update to fix dependency issues in `pypi-publish.dockerfile` affecting the CD pipeline.
- A v2.2 tag was added to the jenkins-shared repo so additional issues can be fix and the tag moved to the latest version.  This will help eliminate having to follow the specific version and update the indy-plenum pipelines each time.

Upgrade pipeline to follow SovrinHelpers v2.2

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/reuseable_test.yaml
.github/workflows/tag.yaml

Node.js 12 deprecation in GHA
Signed-off-by: pSchlarb <p.schlarb@esatus.com>

updated Actions because of

---

plenum/server/node.py
plenum/test/node_catchup/test_ts_store_after_catchup.py

Fixes an issue during catch-up that caused all timestamps to get written into the domain_ledger ts storage, ignoring the config_ledger.
Signed-off-by: Christian Bormann <ChristianCarl.Bormann@de.bosch.com>

correctly pass ledger_id to the timestamp state storage

---

.gitattributes
build-scripts/ubuntu-2004/build-3rd-parties.sh
build-scripts/ubuntu-2004/make_rocksdb.sh

edited make script for rocksdb to include the dependencies

Quickfix for #1632

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/build/Dockerfile.ubuntu-2004
.github/workflows/releasepr.yaml
.github/workflows/reuseable_test.yaml
build-scripts/ubuntu-2004/build-3rd-parties.sh
setup.py

Rocksdbfix

---

.github/workflows/publishRelease.yaml

The BOT_PR_PAT_NODE Secrets needs to be set with a fine grained access token for node so that it can trigger the workflow there. 
Needs https://github.com/hyperledger/indy-node/pull/1812 to be merged first or the trigger won't work.

Trigger Node Update

---

.github/workflows/PR.yaml
.github/workflows/Push.yaml
.github/workflows/publishRelease.yaml
.github/workflows/releasepr.yaml
.github/workflows/reuseable_test.yaml
.github/workflows/tag.yaml

- Address warning raised while running workflows.

Upgrade GHA versions

---

.github/workflows/tag.yaml
build-scripts/ubuntu-2004/build-3rd-parties.sh
dev-setup/ubuntu/ubuntu-2004/SetupVMTest.txt
setup.py

- v3.0.3 is the last version of jsonpickle that contains the setup.py file required by fpm to build the third party package.
- This is intended as an interim fix for the main branch to allow the workflows to complete.
- Work on the `ubuntu-22.04` branch uses `wheel2deb` to build `deb` packages for the newer python modules.

Pin jsonpickle to 3.0.3

---

.github/workflows/publishRelease.yaml

- Update to the latest version of action-download-artifact.
- Do not update the indy-shared-gha actions to v2 on the 20.04 branch. v2 is for the 22.04 branch.

Update action-download-artifact actions

---

setup.py
state/util/utils.py

This package was not critical and features are implemented within hashlib, as pointed out by the package maintainers:
https://github.com/tiran/pysha3
Package is archived.

[Security] Remove sha3 (CVE-2022-37454)

---

.github/workflows/scorecard.yml
README.md

Addresses #1702 by adding the badge and the scorecard task that will execute weekly. Once this is merged, I'll run it manually. Until it has been run at least once. the badge won't generate and the link won't resolve. But that's OK -- we'll get it run.

Add OpenSSF Scorecard and Badge to the repo
